Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010902, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010618, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010176, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009618, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0072, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0054, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0018, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0018, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0054, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0072, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009618, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010176, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010618, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010902, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010902, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010618, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010176, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009618, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0072, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0054, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0018, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0018, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0054, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0072, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009618, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010176, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010618, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010902, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010902, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010618, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010176, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009618, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0072, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0054, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0018, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0018, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0054, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0072, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009618, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010176, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010618, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010902, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010902, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010618, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010176, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009618, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0072, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0054, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0018, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0018, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0054, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0072, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009618, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010176, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010618, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010902, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.010114, -0.003082, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009635, -0.002731, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009259, -0.002496, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008779, -0.002204, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008201, -0.001865, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007528, -0.001486, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006768, -0.001078, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005925, -0.000651, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005008, -0.000214, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004026, 0.000221, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002989, 0.000645, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001907, 0.001049, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000791, 0.001422, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000347, 0.001758, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.001494, 0.00205, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.00264, 0.002291, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003797, 0.002461, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004928, 0.002541, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006016, 0.002536, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007047, 0.002451, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008005, 0.002295, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008877, 0.002081, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009652, 0.00182, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010319, 0.001528, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010869, 0.001216, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011298, 0.000898, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011599, 0.000584, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011771, 0.000283, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011814, 0.0, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.01173, -0.000252, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011523, -0.00046, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011198, -0.000626, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.01076, -0.000754, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010217, -0.000847, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009578, -0.00091, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008848, -0.000951, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008039, -0.000976, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007159, -0.000994, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006218, -0.001013, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.005224, -0.001043, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004188, -0.001091, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003118, -0.001167, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002, -0.001267, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000866, -0.001374, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000269, -0.001491, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001395, -0.001618, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002497, -0.001756, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.003565, -0.001903, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004586, -0.002057, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005548, -0.002214, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006443, -0.002371, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007258, -0.002523, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007985, -0.002666, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008616, -0.002795, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009142, -0.002906, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009559, -0.002996, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010114, -0.003082, 0.033)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.018911, -0.016454, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018345, -0.01578, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.017886, -0.015295, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.017298, -0.014686, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.016585, -0.013966, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.015749, -0.013146, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.014797, -0.012241, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.013734, -0.011266, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012567, -0.010236, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.011306, -0.00917, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009962, -0.008082, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008545, -0.006991, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.007069, -0.005913, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.005548, -0.004864, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.003999, -0.003858, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002433, -0.00291, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.000827, -0.002034, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000773, -0.001272, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002342, -0.000632, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003856, -0.000113, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005291, 0.000284, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006623, 0.000564, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00783, 0.000736, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008893, 0.000807, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009795, 0.000788, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010524, 0.00069, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011068, 0.000521, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011422, 0.000289, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011583, 0.0, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01155, -0.000329, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011326, -0.000683, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010916, -0.001061, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01033, -0.001463, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009581, -0.001889, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008682, -0.00234, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007646, -0.002818, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00649, -0.003327, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005229, -0.00387, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00388, -0.004451, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002459, -0.005074, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000984, -0.005744, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.000529, -0.006464, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002104, -0.00724, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.0037, -0.008033, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.005294, -0.008837, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00687, -0.009647, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008409, -0.010455, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009895, -0.011253, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.011311, -0.01203, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012642, -0.012777, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.013875, -0.013483, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.014995, -0.014136, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.015992, -0.014727, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.016855, -0.015245, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.017574, -0.015682, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018142, -0.016029, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018911, -0.016454, 0.066)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.029127, -0.014637, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.028304, -0.013911, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.027647, -0.013397, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026809, -0.012756, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.025795, -0.012, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.024612, -0.011143, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.023269, -0.010203, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.021776, -0.009197, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.020145, -0.008144, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.018392, -0.007062, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.016531, -0.00597, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.01458, -0.004888, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.012559, -0.003831, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010488, -0.002819, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.00839, -0.001867, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006282, -0.000987, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004138, -0.000205, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002023, 0.000438, 0.099)
boolstatus = Part.InsertCurveFilePoint(3.2e-05, 0.000937, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.001996, 0.001295, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00384, 0.001519, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.005535, 0.001617, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007056, 0.001605, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.008381, 0.001495, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009491, 0.001305, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010371, 0.001048, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011011, 0.000738, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011405, 0.000386, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01155, 0.0, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011449, -0.0004, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011106, -0.000795, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01053, -0.001185, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009733, -0.001572, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00873, -0.001958, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007537, -0.002348, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00617, -0.002746, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.004649, -0.003159, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002993, -0.003594, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00122, -0.004061, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.000648, -0.004566, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002593, -0.005118, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004594, -0.005725, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006681, -0.00639, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008796, -0.007072, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010913, -0.007768, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.013007, -0.008475, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.015056, -0.009186, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.017037, -0.009895, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.018929, -0.010591, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.02071, -0.011265, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.022362, -0.011907, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.023865, -0.012504, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.025205, -0.013048, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026366, -0.013527, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.027334, -0.013932, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.028099, -0.014256, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.029127, -0.014637, 0.099)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.032769, -0.011949, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031836, -0.011253, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031097, -0.010767, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.030154, -0.010162, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.029017, -0.00945, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.027691, -0.008646, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02619, -0.007769, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.024524, -0.006835, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.022708, -0.005863, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02076, -0.004871, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.018697, -0.003877, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.01654, -0.002902, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.014311, -0.00196, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.012033, -0.001069, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.009732, -0.000244, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.007427, 0.000503, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.005091, 0.001145, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.002798, 0.001641, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.000582, 0.00199, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.001526, 0.002199, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003495, 0.002275, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005297, 0.002232, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.006904, 0.002087, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008296, 0.001856, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.009453, 0.001558, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010361, 0.00121, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011011, 0.000827, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011397, 0.000421, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011517, 0.0, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011375, -0.000415, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010978, -0.000802, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010335, -0.001165, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.009459, -0.001505, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008365, -0.001826, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.007069, -0.002135, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005589, -0.002437, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003945, -0.002742, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.002156, -0.003059, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.000241, -0.003398, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.001779, -0.00377, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.003883, -0.004186, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.006052, -0.004654, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.008317, -0.005176, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.010613, -0.005714, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.012912, -0.006266, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.015188, -0.006832, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.017416, -0.007406, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.019573, -0.007983, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.021633, -0.008556, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.023576, -0.009114, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.025378, -0.00965, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02702, -0.010151, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.028484, -0.01061, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.029753, -0.011016, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.030812, -0.01136, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031649, -0.011636, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.032769, -0.011949, 0.132)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.032906, -0.009539, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.031953, -0.0089, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.0312, -0.008459, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.030243, -0.00791, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.029087, -0.007267, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.027742, -0.006542, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.02622, -0.0057540000000000004, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.024533, -0.004918, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.022697, -0.004053, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.020729, -0.003174, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.018649, -0.0023, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.016477, -0.001447, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.014236, -0.000633, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.011949, 0.00013, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.009642, 0.000827, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.007336, 0.001446, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.005004, 0.001961, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002723, 0.002334, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.000524, 0.002566, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.001562, 0.002666, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.003504, 0.002642, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005275, 0.00251, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.00685, 0.002286, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008208, 0.001989, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009332, 0.001637, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010209, 0.001249, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.01083, 0.00084, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011189, 0.000421, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011286, 0.0, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011126, -0.000401, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010715, -0.000763, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010064, -0.001087, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009185, -0.001378, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008091, -0.00164, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.006801, -0.001878, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005329, -0.002101, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.003695, -0.002318, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.001918, -0.002541, 0.165)
boolstatus = Part.InsertCurveFilePoint(1.6e-05, -0.002779, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.001991, -0.003043, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004083, -0.003347, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.006241, -0.003699, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.008497, -0.004099, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.010784, -0.004513, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.013074, -0.004942, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.015343, -0.005384, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.017566, -0.005838, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.019718, -0.006297, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.021775, -0.006757, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.023714, -0.007209, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.025515, -0.007646, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.027157, -0.008057, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.028621, -0.008435, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.02989, -0.008771, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.03095, -0.009057, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.031788, -0.009286, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.032906, -0.009539, 0.165)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.029939, -0.007305, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.029049, -0.006753, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02835, -0.006374, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.027459, -0.005904, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.026385, -0.005353, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.025135, -0.004735, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.023723, -0.004065, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.022158, -0.003356, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.020457, -0.002624, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.018635, -0.001885, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.016711, -0.001153, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.014703, -0.000445, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.012634, 0.000228, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.010524, 0.000851, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.008399, 0.001414, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.006276, 0.001906, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.004134, 0.002301, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.002041, 0.00257, 0.198)
boolstatus = Part.InsertCurveFilePoint(-2.9e-05, 0.002712, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.001876, 0.002738, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.003646, 0.002655, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005257, 0.002478, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.006686, 0.002224, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007915, 0.00191, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.008929, 0.001555, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009717, 0.001173, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010269, 0.00078, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010584, 0.000387, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010659, 0.0, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.0105, -0.000361, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010115, -0.000678, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009511, -0.000953, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.0087, -0.00119, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007694, -0.001394, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00651, -0.001571, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00516, -0.001728, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.003664, -0.001875, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.002036, -0.002021, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.000295, -0.002178, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.001544, -0.002357, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.003461, -0.002567, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.00544, -0.00282, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.007509, -0.003114, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.009608, -0.003419, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.01171, -0.003738, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.013793, -0.00407, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.015834, -0.004414, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.017811, -0.004765, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.019701, -0.005119, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.021484, -0.00547, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02314, -0.005812, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02465, -0.006135, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.025997, -0.006434, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.027165, -0.0067, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02814, -0.006927, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.028912, -0.00711, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.029939, -0.007305, 0.198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.027417, -0.005679, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.0266, -0.0052, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025959, -0.004874, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025144, -0.004469, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.024161, -0.003996, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.023018, -0.003466, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.021726, -0.002892, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.020296, -0.002287, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.018741, -0.001665, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.017078, -0.001038, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.015323, -0.00042, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.013492, 0.000174, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.011607, 0.000735, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.009686, 0.00125, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007752, 0.00171, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005823, 0.002107, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003878, 0.002416, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001981, 0.002611, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.000159, 0.002694, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.001563, 0.002673, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003161, 0.002558, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.004612, 0.002362, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005898, 0.0021, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007002, 0.001789, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00791, 0.001444, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008613, 0.001082, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009103, 0.000714, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009379, 0.000351, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009438, 0.0, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009286, -0.000322, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008931, -0.0006, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008379, -0.000835, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00764, -0.001031, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006727, -0.001193, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005653, -0.001325, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00443, -0.001437, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003074, -0.001535, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.0016, -0.001631, 0.231)
boolstatus = Part.InsertCurveFilePoint(2.2e-05, -0.001733, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001643, -0.001852, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003381, -0.001999, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005175, -0.002183, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007052, -0.002401, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.008955, -0.00263, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.010862, -0.00287, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.012752, -0.003123, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.014604, -0.003387, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.016399, -0.003659, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.018115, -0.003937, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.019734, -0.004213, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.021239, -0.004484, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.02261, -0.004742, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.023835, -0.004981, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.024896, -0.005196, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025783, -0.005379, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.026484, -0.005526, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.027417, -0.005679, 0.231)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.023644, -0.00419, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.02295, -0.0038, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022406, -0.003536, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.021714, -0.003209, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.02088, -0.002827, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.019911, -0.002399, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.018816, -0.001937, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.017604, -0.001451, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.016288, -0.000953, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01488, -0.000452, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.013394, 3.9e-05, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.011846, 0.00051, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.010253, 0.000951, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00863, 0.001354, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006997, 0.00171, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005369, 0.002013, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00373, 0.002242, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.002132, 0.002375, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.000599, 0.002417, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.000848, 0.002372, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002189, 0.00225, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003406, 0.002062, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004483, 0.001821, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005406, 0.001542, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006164, 0.001238, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006749, 0.000922, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007155, 0.000605, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007381, 0.000296, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007425, 0.0, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007292, -0.000268, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006989, -0.000496, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006521, -0.000685, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005898, -0.000838, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005127, -0.00096, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004222, -0.001054, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003192, -0.001128, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002051, -0.00119, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.000811, -0.001247, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.000517, -0.001308, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.001919, -0.001382, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003382, -0.001478, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.004893, -0.001603, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006474, -0.001757, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.008077, -0.001919, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.009684, -0.002091, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.011277, -0.002273, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.012838, -0.002466, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01435, -0.002667, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.015797, -0.002872, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.017163, -0.003079, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.018432, -0.003283, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.019589, -0.003478, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.020621, -0.00366, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.021517, -0.003823, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022265, -0.003963, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022857, -0.004076, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.023644, -0.00419, 0.264)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.020086, -0.00294, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019535, -0.002641, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019104, -0.00244, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018556, -0.00219, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017895, -0.001899, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017127, -0.001573, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016259, -0.001222, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.0153, -0.000854, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.014258, -0.000476, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.013143, -9.8e-05, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011968, 0.000271, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.010744, 0.000624, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.009484, 0.000953, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.008202, 0.001251, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.006913, 0.001513, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.005628, 0.001732, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004334, 0.001894, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003075, 0.00198, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001867, 0.001995, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000729, 0.001943, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000326, 0.001832, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001282, 0.00167, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002127, 0.001468, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00285, 0.001237, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003443, 0.000989, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.0039, 0.000734, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004217, 0.00048, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00439, 0.000234, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004422, 0.0, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004314, -0.00021, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004073, -0.000386, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003703, -0.000529, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00321, -0.000642, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002602, -0.000729, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001888, -0.000793, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001077, -0.00084, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000177, -0.000875, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.0008, -0.000905, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001846, -0.000938, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00295, -0.00098, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004103, -0.001039, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.005294, -0.00112, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00654, -0.001223, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.007805, -0.001332, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.009072, -0.001449, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.010328, -0.001574, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011559, -0.001707, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.012752, -0.001848, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.013894, -0.001993, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.014971, -0.002141, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.015972, -0.002286, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016886, -0.002427, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017701, -0.002558, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018408, -0.002676, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018999, -0.002777, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019466, -0.002859, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020086, -0.00294, 0.297)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.015714, -0.001721, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015354, -0.001531, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015072, -0.001404, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014714, -0.001246, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014282, -0.001062, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013781, -0.000856, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013215, -0.000635, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012589, -0.000403, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011909, -0.000165, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011182, 7.1e-05, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010415, 0.000302, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009617, 0.000522, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.008796, 0.000726, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007961, 0.00091, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007121, 0.00107, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006285, 0.001203, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005443, 0.001298, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004624, 0.001344, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00384, 0.001345, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.0031, 0.001302, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002416, 0.001222, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001796, 0.001109, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001249, 0.000971, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000781, 0.000816, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000397, 0.00065, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000102, 0.000481, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000101, 0.000313, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000212, 0.000152, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000231, 0.0, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000159, -0.000135, 0.33)
boolstatus = Part.InsertCurveFilePoint(1.0e-06, -0.000248, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00024, -0.000338, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000562, -0.000408, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000957, -0.00046, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001421, -0.000496, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001949, -0.00052, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002533, -0.000535, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003169, -0.000548, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003848, -0.000561, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004566, -0.00058, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005316, -0.000609, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00609, -0.000653, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006901, -0.00071, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007723, -0.000771, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.008547, -0.000837, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009364, -0.000909, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010165, -0.000986, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010941, -0.001068, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011684, -0.001154, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012385, -0.001241, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013037, -0.001328, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013631, -0.001412, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014162, -0.001491, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014622, -0.001562, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015006, -0.001624, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015311, -0.001674, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015714, -0.001721, 0.33)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.011, -2.4492127076447544e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.011, -2.4492127076447544e-19, 0.0198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.01011351, -0.00308171, 0.033, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.018911189999999998, -0.01645377, 0.066, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.029126830000000003, -0.01463654, 0.099, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.03276923000000001, -0.01194934, 0.132, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.0329063, -0.00953857, 0.165, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.02993907, -0.0073047500000000005, 0.198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.02741701, -0.005679109999999999, 0.23099999999999998, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.023643789999999998, -0.00418962, 0.264, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.020086310000000003, -0.00293979, 0.297, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.015714399999999993, -0.0017209600000000001, 0.33, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
