Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010902, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010618, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010176, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009618, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0072, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0054, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0018, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0018, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0054, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0072, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009618, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010176, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010618, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010902, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010902, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010618, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.010176, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009618, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.009, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0072, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0054, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0018, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0018, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0054, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0072, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.009618, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010176, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010618, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.010902, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010902, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010618, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010176, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009618, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0072, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0054, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0018, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0018, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0054, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0072, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009618, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010176, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010618, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010902, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010902, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010618, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.010176, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009618, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.009, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0072, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0054, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0018, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0018, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0054, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0072, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.009618, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010176, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010618, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.010902, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011, 0.0, 0.0198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.010114, -0.003082, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009635, -0.002731, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009259, -0.002496, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008779, -0.002204, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008201, -0.001865, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007528, -0.001486, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006768, -0.001078, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005925, -0.000651, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005008, -0.000214, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004026, 0.000221, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002989, 0.000645, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001907, 0.001049, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000791, 0.001422, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000347, 0.001758, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.001494, 0.00205, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.00264, 0.002291, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003797, 0.002461, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004928, 0.002541, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006016, 0.002536, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007047, 0.002451, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008005, 0.002295, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008877, 0.002081, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009652, 0.00182, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010319, 0.001528, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010869, 0.001216, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011298, 0.000898, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011599, 0.000584, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011771, 0.000283, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011814, 0.0, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.01173, -0.000252, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011523, -0.00046, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011198, -0.000626, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.01076, -0.000754, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010217, -0.000847, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009578, -0.00091, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008848, -0.000951, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008039, -0.000976, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007159, -0.000994, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006218, -0.001013, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.005224, -0.001043, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004188, -0.001091, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003118, -0.001167, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002, -0.001267, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000866, -0.001374, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000269, -0.001491, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001395, -0.001618, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002497, -0.001756, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.003565, -0.001903, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004586, -0.002057, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005548, -0.002214, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006443, -0.002371, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007258, -0.002523, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007985, -0.002666, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008616, -0.002795, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009142, -0.002906, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009559, -0.002996, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010114, -0.003082, 0.033)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.020977, -0.011851, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.02032, -0.011267, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.019795, -0.010853, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.019125, -0.010337, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018314, -0.009728, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.017369, -0.009037, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.016295, -0.00828, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.015101, -0.00747, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.013797, -0.006621, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012395, -0.005748, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.010907, -0.004868, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009347, -0.003994, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00773, -0.003142, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006073, -0.002324, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.004394, -0.001555, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002707, -0.000844, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00099, -0.00021, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000703, 0.000311, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002348, 0.000717, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003922, 0.00101, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005399, 0.001195, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006757, 0.001279, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007977, 0.001273, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009039, 0.001189, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009929, 0.00104, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010635, 0.000836, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011149, 0.00059, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011465, 0.000309, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011583, 0.0, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011503, -0.000321, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011229, -0.000639, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010769, -0.000953, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010131, -0.001265, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009328, -0.001578, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008373, -0.001894, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007279, -0.002217, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006061, -0.002552, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.004735, -0.002906, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003315, -0.003285, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.001819, -0.003695, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000262, -0.004144, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00134, -0.004636, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00301, -0.005175, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.004704, -0.005728, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006398, -0.006292, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008075, -0.006865, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009715, -0.007441, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.011301, -0.008015, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012815, -0.008578, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.014241, -0.009124, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.015563, -0.009643, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.016766, -0.010127, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.017839, -0.010566, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018767, -0.010954, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.019542, -0.011281, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.020155, -0.011543, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.020977, -0.011851, 0.066)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.029127, -0.014637, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.028304, -0.013911, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.027647, -0.013397, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026809, -0.012756, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.025795, -0.012, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.024612, -0.011143, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.023269, -0.010203, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.021776, -0.009197, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.020145, -0.008144, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.018392, -0.007062, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.016531, -0.00597, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.01458, -0.004888, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.012559, -0.003831, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010488, -0.002819, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.00839, -0.001867, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006282, -0.000987, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004138, -0.000205, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002023, 0.000438, 0.099)
boolstatus = Part.InsertCurveFilePoint(3.2e-05, 0.000937, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.001996, 0.001295, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00384, 0.001519, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.005535, 0.001617, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007056, 0.001605, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.008381, 0.001495, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009491, 0.001305, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010371, 0.001048, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011011, 0.000738, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011405, 0.000386, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01155, 0.0, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011449, -0.0004, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011106, -0.000795, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01053, -0.001185, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009733, -0.001572, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00873, -0.001958, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007537, -0.002348, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00617, -0.002746, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.004649, -0.003159, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002993, -0.003594, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00122, -0.004061, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.000648, -0.004566, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002593, -0.005118, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004594, -0.005725, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006681, -0.00639, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008796, -0.007072, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010913, -0.007768, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.013007, -0.008475, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.015056, -0.009186, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.017037, -0.009895, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.018929, -0.010591, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.02071, -0.011265, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.022362, -0.011907, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.023865, -0.012504, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.025205, -0.013048, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026366, -0.013527, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.027334, -0.013932, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.028099, -0.014256, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.029127, -0.014637, 0.099)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.032769, -0.011949, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031836, -0.011253, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031097, -0.010767, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.030154, -0.010162, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.029017, -0.00945, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.027691, -0.008646, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02619, -0.007769, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.024524, -0.006835, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.022708, -0.005863, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02076, -0.004871, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.018697, -0.003877, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.01654, -0.002902, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.014311, -0.00196, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.012033, -0.001069, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.009732, -0.000244, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.007427, 0.000503, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.005091, 0.001145, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.002798, 0.001641, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.000582, 0.00199, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.001526, 0.002199, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003495, 0.002275, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005297, 0.002232, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.006904, 0.002087, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008296, 0.001856, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.009453, 0.001558, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010361, 0.00121, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011011, 0.000827, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011397, 0.000421, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011517, 0.0, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011375, -0.000415, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010978, -0.000802, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010335, -0.001165, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.009459, -0.001505, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008365, -0.001826, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.007069, -0.002135, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005589, -0.002437, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003945, -0.002742, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.002156, -0.003059, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.000241, -0.003398, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.001779, -0.00377, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.003883, -0.004186, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.006052, -0.004654, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.008317, -0.005176, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.010613, -0.005714, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.012912, -0.006266, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.015188, -0.006832, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.017416, -0.007406, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.019573, -0.007983, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.021633, -0.008556, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.023576, -0.009114, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.025378, -0.00965, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02702, -0.010151, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.028484, -0.01061, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.029753, -0.011016, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.030812, -0.01136, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031649, -0.011636, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.032769, -0.011949, 0.132)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.032936, -0.0094, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.03198, -0.008764, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.031227, -0.008326, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.030267, -0.00778, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.02911, -0.00714, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.027762, -0.00642, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.026238, -0.005636, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.024548, -0.004806, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.022709, -0.003946, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.020739, -0.003073, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.018657, -0.002206, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.016482, -0.00136, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.014238, -0.000552, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.011948, 0.000203, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.009639, 0.000892, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.007331, 0.001505, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004998, 0.002012, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002715, 0.002378, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.000515, 0.002603, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.001571, 0.002697, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.003513, 0.002667, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005283, 0.002528, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.006857, 0.0023, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008215, 0.001998, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009337, 0.001644, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010213, 0.001253, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010832, 0.000841, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.01119, 0.000421, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011286, 0.0, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011124, -0.0004, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010713, -0.000761, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010061, -0.001084, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009181, -0.001371, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008086, -0.001629, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.006795, -0.001864, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005322, -0.002083, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.003688, -0.002295, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.00191, -0.002511, 0.165)
boolstatus = Part.InsertCurveFilePoint(7.0e-06, -0.002743, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002001, -0.003002, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004094, -0.003299, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.006253, -0.003644, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.008509, -0.004037, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.010798, -0.004444, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.01309, -0.004865, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.01536, -0.005301, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.017584, -0.005747, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.019737, -0.0062, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.021796, -0.006653, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.023737, -0.007099, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.025539, -0.00753, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.027182, -0.007936, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.028647, -0.00831, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.029918, -0.008642, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.030979, -0.008924, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.031817, -0.009151, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.032936, -0.0094, 0.165)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.029964, -0.007163, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.029073, -0.006614, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.028372, -0.006238, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.027479, -0.005771, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.026403, -0.005224, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.025152, -0.00461, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.023737, -0.003945, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02217, -0.003241, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.020466, -0.002515, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.018641, -0.001782, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.016714, -0.001058, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.014704, -0.000356, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.012633, 0.000309, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.010521, 0.000925, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.008393, 0.00148, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.006269, 0.001965, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.004125, 0.002353, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.002032, 0.002614, 0.198)
boolstatus = Part.InsertCurveFilePoint(-1.9e-05, 0.00275, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.001886, 0.002768, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.003656, 0.002679, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005266, 0.002497, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.006694, 0.002238, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007922, 0.00192, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.008935, 0.001561, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009721, 0.001177, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010272, 0.000782, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010585, 0.000387, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010659, 0.0, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010499, -0.00036, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010112, -0.000676, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009507, -0.000949, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.008695, -0.001184, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00769, -0.001384, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.006504, -0.001556, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005154, -0.001709, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.003657, -0.00185, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.002029, -0.001991, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.000287, -0.002142, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.001552, -0.002314, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.00347, -0.002518, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.00545, -0.002764, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.00752, -0.00305, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.00962, -0.003349, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.011723, -0.00366, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.013807, -0.003985, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.015849, -0.004321, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.017827, -0.004666, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.019718, -0.005013, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.021503, -0.005358, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02316, -0.005694, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.024671, -0.006012, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.026019, -0.006306, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.027188, -0.006568, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.028164, -0.006792, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.028936, -0.006972, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.029964, -0.007163, 0.198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.027433, -0.005576, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.026615, -0.0051, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025973, -0.004775, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025156, -0.004373, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.024172, -0.003903, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.023027, -0.003376, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.021733, -0.002805, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.020302, -0.002204, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.018746, -0.001586, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.017081, -0.000964, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.015324, -0.000351, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.013492, 0.000238, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.011605, 0.000794, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.009683, 0.001304, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007748, 0.001758, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005817, 0.00215, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003871, 0.002453, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001974, 0.002643, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.000152, 0.002721, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.001571, 0.002695, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003168, 0.002576, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.004619, 0.002375, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005904, 0.00211, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007007, 0.001796, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007914, 0.001449, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008616, 0.001084, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009105, 0.000715, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00938, 0.000351, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009438, 0.0, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009285, -0.000322, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008929, -0.000599, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008376, -0.000832, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007637, -0.001026, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006724, -0.001185, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005649, -0.001315, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.004426, -0.001423, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003069, -0.001518, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.001595, -0.001609, 0.231)
boolstatus = Part.InsertCurveFilePoint(1.7e-05, -0.001707, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001649, -0.001822, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003386, -0.001964, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005181, -0.002142, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007058, -0.002355, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.008963, -0.002578, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.01087, -0.002813, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.012761, -0.003061, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.014614, -0.00332, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.016409, -0.003587, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.018126, -0.00386, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.019746, -0.004132, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.021251, -0.004399, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.022624, -0.004653, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.023848, -0.004889, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.02491, -0.0051, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025798, -0.00528, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.026499, -0.005426, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.027433, -0.005576, 0.231)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.023691, -0.003821, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022993, -0.00344, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022446, -0.003182, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.02175, -0.002863, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.020911, -0.002491, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.019937, -0.002075, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.018837, -0.001626, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01762, -0.001154, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.016297, -0.000671, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.014884, -0.000187, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.013392, 0.000286, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.011839, 0.000739, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01024, 0.001161, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.008613, 0.001544, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006976, 0.001881, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005345, 0.002165, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003702, 0.002374, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.002103, 0.002489, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00057, 0.002512, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.000877, 0.00245, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002216, 0.002312, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003431, 0.002109, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004505, 0.001856, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005424, 0.001566, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006178, 0.001253, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.00676, 0.00093, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007162, 0.000609, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007384, 0.000297, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007425, 0.0, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007289, -0.000267, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006983, -0.000491, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006513, -0.000674, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005888, -0.00082, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005116, -0.000932, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.00421, -0.001016, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003179, -0.001078, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002037, -0.001126, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.000796, -0.001168, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.000532, -0.001213, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.001935, -0.001271, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003399, -0.001349, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.004911, -0.001457, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006493, -0.001592, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.008099, -0.001735, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.009708, -0.001888, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.011302, -0.002051, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.012865, -0.002225, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01438, -0.002408, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01583, -0.002597, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.017198, -0.002787, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.018469, -0.002976, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.019628, -0.003157, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.020663, -0.003327, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.02156, -0.003479, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.02231, -0.00361, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022903, -0.003716, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.023691, -0.003821, 0.264)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.020136, -0.002494, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019579, -0.002206, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019145, -0.002012, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018592, -0.001772, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017925, -0.001493, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017152, -0.001182, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016278, -0.000847, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.015312, -0.000495, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.014263, -0.000137, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.013142, 0.00022, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011961, 0.000568, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.01073, 0.000899, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.009465, 0.001205, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.008178, 0.00148, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.006884, 0.001718, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.005594, 0.001914, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004298, 0.002052, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003038, 0.002116, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00183, 0.002109, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000692, 0.002037, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00036, 0.001906, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001313, 0.001726, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002154, 0.001509, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002873, 0.001266, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003461, 0.001007, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003914, 0.000743, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004225, 0.000483, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004395, 0.000234, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004422, 0.0, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004311, -0.000208, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004066, -0.000379, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003693, -0.000516, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003198, -0.00062, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002589, -0.000696, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001874, -0.000747, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001062, -0.000779, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000162, -0.000797, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000815, -0.00081, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001862, -0.000824, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002967, -0.000846, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004121, -0.000884, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.005313, -0.000944, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.006561, -0.001024, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.007827, -0.00111, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.009096, -0.001203, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.010354, -0.001306, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011587, -0.001417, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.012783, -0.001536, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.013927, -0.001661, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.015007, -0.001788, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016011, -0.001916, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016926, -0.002039, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017744, -0.002156, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018453, -0.002261, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019045, -0.002352, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019514, -0.002425, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020136, -0.002494, 0.297)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.015746, -0.001398, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015382, -0.001215, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015098, -0.001093, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014736, -0.000943, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014301, -0.000767, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013795, -0.000572, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013225, -0.000362, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012594, -0.000143, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011909, 8.0e-05, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011178, 0.000303, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010407, 0.000518, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009605, 0.000722, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00878, 0.000909, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007941, 0.001076, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007098, 0.001219, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006259, 0.001335, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005416, 0.001412, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004596, 0.001442, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003812, 0.001427, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003073, 0.001369, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002391, 0.001275, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001773, 0.00115, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001229, 0.001001, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000764, 0.000836, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000384, 0.000663, 0.33)
boolstatus = Part.InsertCurveFilePoint(-9.3e-05, 0.000488, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000108, 0.000316, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000215, 0.000152, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000231, 0.0, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000157, -0.000134, 0.33)
boolstatus = Part.InsertCurveFilePoint(-4.0e-06, -0.000243, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000247, -0.000329, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00057, -0.000392, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000966, -0.000435, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001431, -0.000462, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001959, -0.000475, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002544, -0.000479, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003179, -0.000479, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003859, -0.000478, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004577, -0.000482, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005327, -0.000497, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006102, -0.000525, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006913, -0.000565, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007737, -0.00061, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.008562, -0.000659, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00938, -0.000714, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010183, -0.000775, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.01096, -0.000842, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011705, -0.000912, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012407, -0.000985, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013061, -0.001059, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.013657, -0.001131, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.014189, -0.001199, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.01465, -0.001261, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015036, -0.001315, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015341, -0.001359, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.015746, -0.001398, 0.33)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.011, -2.4492935982947063e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.011, -2.4492935982947063e-19, 0.0198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.01011351, -0.00308171, 0.033, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.02097735, -0.011851, 0.066, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.029126830000000003, -0.01463654, 0.099, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.03276923000000001, -0.01194934, 0.132, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.03293605, -0.00939969, 0.165, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.02996432, -0.00716299, 0.198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.02743273, -0.00557617, 0.23099999999999998, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.023691320000000002, -0.0038206000000000004, 0.264, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.020135640000000003, -0.0024944700000000004, 0.297, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.015745969999999995, -0.0013977999999999998, 0.33, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
