Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011814, 0.0, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.011325, 0.000278, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010942, 0.000466, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010455, 0.0007, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009867, 0.000973, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009184, 0.001279, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008413, 0.00161, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007559, 0.001958, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006631, 0.002315, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005639, 0.002674, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004591, 0.003027, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.0035, 0.003366, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002376, 0.003684, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001232, 0.003975, 0.033)
boolstatus = Part.InsertCurveFilePoint(-8.0e-05, 0.004233, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.001069, 0.004453, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002226, 0.004621, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003354, 0.004722, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004436, 0.004757, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.005459, 0.004731, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006407, 0.00465, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007267, 0.004522, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008028, 0.004357, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008681, 0.004163, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009218, 0.003951, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009632, 0.00373, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009921, 0.003508, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010081, 0.003291, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010114, 0.003082, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010021, 0.002892, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009807, 0.002729, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009478, 0.002594, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009038, 0.002484, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008495, 0.002395, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007856, 0.002325, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007128, 0.002268, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006323, 0.00222, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.005447, 0.002175, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.004509, 0.002127, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003519, 0.002069, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002486, 0.001995, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.00142, 0.001901, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000304, 0.001786, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000828, 0.001665, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001962, 0.001537, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.003087, 0.001402, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004188, 0.00126, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005256, 0.001112, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006277, 0.000961, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007241, 0.00081, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008136, 0.000661, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008953, 0.000518, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009681, 0.000386, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010313, 0.000267, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010841, 0.000166, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.011259, 8.3e-05, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.011814, 0.0, 0.033)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011583, 0.0, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.011017, 0.000673, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.010558, 0.001159, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.00997, 0.001767, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009257, 0.002488, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008421, 0.003308, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.007469, 0.004213, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006406, 0.005188, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.005239, 0.006217, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.003978, 0.007284, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002634, 0.008372, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.001217, 0.009463, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000259, 0.010541, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00178, 0.01159, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00333, 0.012595, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.004895, 0.013544, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006502, 0.01442, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008101, 0.015182, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00967, 0.015822, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011184, 0.016341, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.012619, 0.016738, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.013951, 0.017018, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.015158, 0.01719, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.016221, 0.017261, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.017124, 0.017242, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.017852, 0.017144, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018396, 0.016975, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01875, 0.016743, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018911, 0.016454, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018879, 0.016124, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018654, 0.01577, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018244, 0.015393, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.017659, 0.014991, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01691, 0.014565, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01601, 0.014114, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.014974, 0.013636, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.013818, 0.013127, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.012557, 0.012584, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011208, 0.012003, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009787, 0.01138, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008312, 0.01071, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006799, 0.00999, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005224, 0.009214, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003629, 0.008421, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002034, 0.007617, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.000459, 0.006807, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.001081, 0.005999, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002567, 0.005201, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.003983, 0.004423, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.005314, 0.003677, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006547, 0.002971, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.007667, 0.002318, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008664, 0.001727, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.009527, 0.001209, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.010246, 0.000772, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.010814, 0.000424, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.011583, 0.0, 0.066)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01155, 0.0, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010727, 0.000726, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.01007, 0.001239, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.009232, 0.001881, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008218, 0.002637, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.007035, 0.003494, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.005692, 0.004434, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004199, 0.005439, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002568, 0.006492, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.000815, 0.007574, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.001046, 0.008666, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002996, 0.009749, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.005017, 0.010805, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007089, 0.011817, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009187, 0.01277, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011294, 0.013649, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.013439, 0.014432, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.015554, 0.015074, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.017609, 0.015573, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.019573, 0.015932, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.021417, 0.016155, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.023112, 0.016254, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.024633, 0.016241, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.025958, 0.016132, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.027068, 0.015941, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.027948, 0.015684, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.028588, 0.015375, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.028981, 0.015023, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.029127, 0.014637, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.029026, 0.014236, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.028682, 0.013841, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.028107, 0.013451, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.02731, 0.013064, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.026307, 0.012678, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.025114, 0.012289, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.023747, 0.011891, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.022226, 0.011478, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.020569, 0.011042, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.018797, 0.010576, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.016928, 0.010071, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.014984, 0.009518, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.012983, 0.008911, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010896, 0.008247, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.008781, 0.007565, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.006664, 0.006868, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00457, 0.006161, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002521, 0.00545, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00054, 0.004742, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.001352, 0.004046, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.003133, 0.003372, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.004785, 0.00273, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006289, 0.002132, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.007628, 0.001588, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008789, 0.001109, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.009757, 0.000704, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010522, 0.000381, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.01155, 0.0, 0.099)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011517, 0.0, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.010584, 0.000696, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.009844, 0.001182, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.008902, 0.001788, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.007764, 0.0025, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.006439, 0.003303, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.004937, 0.00418, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.003271, 0.005114, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.001456, 0.006087, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.000493, 0.007079, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.002555, 0.008072, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.004712, 0.009048, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.006941, 0.009989, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.009219, 0.01088, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.01152, 0.011705, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.013826, 0.012452, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.016161, 0.013094, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.018454, 0.01359, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.02067, 0.013939, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.022778, 0.014148, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.024748, 0.014224, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.026549, 0.014182, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.028156, 0.014036, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.029548, 0.013805, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.030705, 0.013508, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.031614, 0.01316, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.032263, 0.012777, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.032649, 0.012371, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.032769, 0.011949, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.032627, 0.011535, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.03223, 0.011147, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.031587, 0.010784, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.030711, 0.010444, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.029617, 0.010123, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.028321, 0.009815, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.026841, 0.009512, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.025197, 0.009208, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.023408, 0.008891, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.021493, 0.008551, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.019473, 0.008179, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.017369, 0.007764, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.0152, 0.007295, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.012936, 0.006774, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010639, 0.006236, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008341, 0.005683, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.006065, 0.005117, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003836, 0.004543, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.001679, 0.003966, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.000381, 0.003394, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.002323, 0.002836, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.004126, 0.0023, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.005768, 0.001798, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.007232, 0.00134, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.008501, 0.000934, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.00956, 0.000589, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.010397, 0.000314, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.011517, 0.0, 0.132)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011286, 0.0, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.010374, 0.00061, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.009655, 0.001032, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.008739, 0.001557, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.007634, 0.002173, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.006348, 0.002865, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004892, 0.003619, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.003279, 0.004418, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.001524, 0.005246, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.000358, 0.006086, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.002346, 0.006922, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.004423, 0.007737, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.006566, 0.008516, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008753, 0.009245, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010959, 0.009911, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.013165, 0.010504, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.015394, 0.010995, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.017576, 0.011352, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.019678, 0.011575, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.021673, 0.01167, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.02353, 0.011647, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.025223, 0.01152, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.026729, 0.011306, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.028028, 0.011022, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.029103, 0.010687, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.029941, 0.010316, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.030534, 0.009924, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.030878, 0.009523, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.030971, 0.009121, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.030817, 0.008737, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.030425, 0.008391, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.029803, 0.008081, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.028962, 0.007803, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.027916, 0.007553, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.026682, 0.007325, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.025274, 0.007112, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.023712, 0.006904, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.022013, 0.006692, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.020194, 0.006464, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.018275, 0.006211, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.016275, 0.00592, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.014211, 0.005584, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.012055, 0.005202, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009867, 0.004806, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.007677, 0.004396, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005508, 0.003972, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.003383, 0.003539, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.001325, 0.003099, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.000642, 0.00266, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002497, 0.002227, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004219, 0.00181, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.005788, 0.001417, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.007188, 0.001055, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.008402, 0.000734, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.009416, 0.000461, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.010217, 0.000241, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.011286, 0.0, 0.165)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.010659, 0.0, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.009773, 0.00055, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.009076, 0.000927, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.008189, 0.001395, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.007119, 0.001944, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.005875, 0.002559, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.004467, 0.003227, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.002909, 0.003933, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.001214, 0.004662, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.0006, 0.005398, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.002517, 0.006127, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.004516, 0.006833, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.006577, 0.007502, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.008678, 0.008123, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010795, 0.008683, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.01291, 0.009174, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.015043, 0.009568, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.017127, 0.009835, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.019132, 0.009977, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.021029, 0.010002, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.022792, 0.009919, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.024396, 0.009743, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.02582, 0.009491, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.027044, 0.009178, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.028054, 0.008824, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.028838, 0.008444, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.029388, 0.008053, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.029702, 0.007661, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.029777, 0.007276, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.029618, 0.006916, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.029234, 0.006601, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.028633, 0.006326, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.027825, 0.00609, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.026824, 0.005887, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.025644, 0.005711, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.0243, 0.005554, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.022809, 0.005408, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.021188, 0.005262, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.019454, 0.005106, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.017623, 0.004928, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.015713, 0.004718, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.013742, 0.004466, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.011681, 0.004174, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009591, 0.00387, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007497, 0.003552, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005422, 0.003222, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00339, 0.00288, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.001421, 0.00253, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.000462, 0.002177, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.002238, 0.001827, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.003887, 0.001487, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.005391, 0.001165, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.006732, 0.000868, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.007896, 0.000602, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.008867, 0.000376, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.009636, 0.000194, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.010659, 0.0, 0.198)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.009438, 0.0, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.008621, 0.000479, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.00798, 0.000805, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007165, 0.00121, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.006182, 0.001683, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005039, 0.002213, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003746, 0.002787, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.002317, 0.003392, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.000762, 0.004015, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.000901, 0.004641, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.002657, 0.005259, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.004487, 0.005853, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006372, 0.006414, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008293, 0.006929, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.010227, 0.00739, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.012156, 0.007786, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.014101, 0.008095, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.015998, 0.00829, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.01782, 0.008373, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.019542, 0.008353, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.02114, 0.008237, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.022591, 0.008041, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.023877, 0.007779, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.024981, 0.007468, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.025889, 0.007123, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.026592, 0.006761, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.027082, 0.006393, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.027358, 0.00603, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.027417, 0.005679, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.027265, 0.005357, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.02691, 0.005079, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.026358, 0.004844, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.025619, 0.004648, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.024706, 0.004486, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.023632, 0.004354, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.022409, 0.004242, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.021053, 0.004144, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.019579, 0.004048, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.018001, 0.003946, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.016336, 0.003827, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.014598, 0.00368, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.012804, 0.003496, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.010927, 0.003278, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009024, 0.003049, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007117, 0.002809, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005227, 0.002556, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003375, 0.002292, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00158, 0.00202, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.000136, 0.001742, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001755, 0.001466, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.00326, 0.001195, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.004631, 0.000937, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005856, 0.000698, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.006917, 0.000484, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007804, 0.0003, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.008505, 0.000153, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.009438, 0.0, 0.231)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007425, 0.0, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006731, 0.000389, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006187, 0.000653, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005495, 0.000981, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.004661, 0.001363, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003692, 0.00179, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.002597, 0.002252, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.001385, 0.002738, 0.264)
boolstatus = Part.InsertCurveFilePoint(-6.9e-05, 0.003237, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.001339, 0.003738, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002824, 0.004229, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004372, 0.0047, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005966, 0.005141, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007589, 0.005544, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.009221, 0.0059, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.01085, 0.006202, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.012489, 0.006431, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.014087, 0.006565, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.01562, 0.006606, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.017067, 0.006562, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.018408, 0.006439, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.019625, 0.006251, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.020702, 0.006011, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.021624, 0.005732, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.022382, 0.005428, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.022967, 0.005112, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.023374, 0.004795, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.023599, 0.004486, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.023644, 0.00419, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.023511, 0.003921, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.023208, 0.003693, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.02274, 0.003504, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.022116, 0.003351, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.021346, 0.00323, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.020441, 0.003135, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.019411, 0.003061, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.01827, 0.003, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.017029, 0.002943, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.015702, 0.002882, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.0143, 0.002808, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.012837, 0.002712, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.011326, 0.002586, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.009745, 0.002432, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.008141, 0.002271, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006535, 0.002099, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004942, 0.001916, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003381, 0.001724, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.001869, 0.001523, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.000422, 0.001317, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.000944, 0.00111, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.002213, 0.000906, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00337, 0.000711, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.004403, 0.00053, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005298, 0.000367, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006047, 0.000227, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006638, 0.000114, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.007425, 0.0, 0.264)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.004422, 0.0, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003871, 0.000299, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00344, 0.0005, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002891, 0.00075, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00223, 0.001041, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001462, 0.001366, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000595, 0.001718, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000365, 0.002086, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001407, 0.002464, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002521, 0.002841, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003696, 0.003211, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00492, 0.003564, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.00618, 0.003893, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.007462, 0.004191, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.008751, 0.004453, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.010037, 0.004672, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.01133, 0.004833, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.01259, 0.00492, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.013797, 0.004935, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.014936, 0.004883, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.01599, 0.004771, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.016946, 0.004609, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.017791, 0.004408, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.018514, 0.004177, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019107, 0.003929, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019564, 0.003674, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019881, 0.00342, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.020055, 0.003173, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.020086, 0.00294, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019979, 0.00273, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019737, 0.002554, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019367, 0.002411, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.018874, 0.002297, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.018266, 0.002211, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.017553, 0.002147, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.016741, 0.0021, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.015842, 0.002065, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.014864, 0.002035, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.013818, 0.002002, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.012714, 0.00196, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.011561, 0.001901, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.01037, 0.00182, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.009124, 0.001717, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.007859, 0.001608, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.006593, 0.001491, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.005337, 0.001366, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004105, 0.001232, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002912, 0.001092, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001771, 0.000946, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000693, 0.000799, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000308, 0.000653, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001221, 0.000513, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002036, 0.000382, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002743, 0.000264, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003334, 0.000163, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003801, 8.0e-05, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004422, 0.0, 0.297)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.000231, 0.0, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000129, 0.00019, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000411, 0.000317, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000769, 0.000475, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.001201, 0.000659, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.001702, 0.000865, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.002269, 0.001086, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.002895, 0.001318, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.003575, 0.001556, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.004302, 0.001792, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.005068, 0.002023, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.005866, 0.002243, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.006687, 0.002447, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.007522, 0.002631, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.008362, 0.002791, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.009199, 0.002924, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.01004, 0.003019, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.010859, 0.003065, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.011644, 0.003066, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.012383, 0.003023, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.013067, 0.002943, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.013687, 0.00283, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.014235, 0.002692, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.014703, 0.002537, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015086, 0.002371, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015381, 0.002202, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015585, 0.002034, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015696, 0.001873, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015714, 0.001721, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015643, 0.001585, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015485, 0.001473, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.015243, 0.001383, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.014922, 0.001313, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.014526, 0.001261, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.014062, 0.001225, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.013535, 0.001201, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.01295, 0.001185, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.012315, 0.001173, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.011635, 0.00116, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.010917, 0.001141, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.010168, 0.001112, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.009393, 0.001068, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.008583, 0.001011, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.00776, 0.00095, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.006936, 0.000884, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.00612, 0.000812, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.005319, 0.000735, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.004542, 0.000653, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.0038, 0.000567, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.003098, 0.00048, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.002447, 0.000393, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.001852, 0.000309, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.001322, 0.00023, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000862, 0.000159, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000477, 9.7e-05, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000173, 4.7e-05, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000231, 0.0, 0.33)
boolstatus = Part.InsertCurveFileEnd()
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.011814000000000002, 0.0, 0.033, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.011583000000000001, 0.0, 0.066, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.011550000000000001, 0.0, 0.099, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.011517, 0.0, 0.132, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.011286, 0.0, 0.165, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.010659, 0.0, 0.198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.009438, 0.0, 0.23099999999999998, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.007425000000000001, 0.0, 0.264, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.004421999999999997, 0.0, 0.297, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.00023100000000000431, 0.0, 0.33, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
