Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006951, 0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006809, 0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006588, 0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006309, 0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0048, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0024, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0012, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0012, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0024, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0048, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006309, 0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006588, 0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006809, 0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006951, 0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006951, -0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006809, -0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006588, -0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006309, -0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0048, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0024, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0012, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0012, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0024, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0048, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006309, -0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006809, -0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006951, -0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006951, 0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006809, 0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006588, 0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006309, 0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0048, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0024, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0012, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0012, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0024, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0048, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006309, 0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006588, 0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006809, 0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006951, 0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006951, -0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006809, -0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006588, -0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006309, -0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0048, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0024, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0012, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0012, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0024, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0048, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006309, -0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006809, -0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006951, -0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.008424, -0.002121, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.008094, -0.001886, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007834, -0.001727, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007504, -0.001532, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007105, -0.001303, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006641, -0.001049, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006117, -0.000774, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005536, -0.000487, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004904, -0.000193, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004227, 0.0001, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003513, 0.000387, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002767, 0.000659, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001998, 0.000911, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001215, 0.001139, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000425, 0.001337, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000364, 0.001501, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001161, 0.001618, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001938, 0.001675, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002687, 0.001674, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003396, 0.001621, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004054, 0.00152, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004654, 0.001379, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005186, 0.001208, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005644, 0.001015, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006021, 0.000808, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006315, 0.000598, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006521, 0.000389, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006639, 0.000189, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006609, -0.000168, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006466, -0.000308, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006242, -0.00042, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.00594, -0.000506, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005567, -0.00057, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005126, -0.000614, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004625, -0.000643, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004068, -0.000662, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003463, -0.000677, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002815, -0.000692, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002132, -0.000715, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001419, -0.000751, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000683, -0.000804, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-8.7e-05, -0.000874, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000867, -0.000949, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001648, -0.001031, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002423, -0.001119, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003181, -0.001214, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003916, -0.001315, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004619, -0.001421, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005282, -0.001528, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005897, -0.001636, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006458, -0.00174, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006959, -0.001837, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007393, -0.001925, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007756, -0.002001, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.008042, -0.002062, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.008424, -0.002121, 0.01905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.016604, -0.00847, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.016134, -0.008053, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015759, -0.007757, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01528, -0.007388, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014701, -0.006952, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014025, -0.006459, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.013257, -0.005918, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.012404, -0.005339, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011472, -0.004732, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01047, -0.004108, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009407, -0.003479, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008291, -0.002855, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007136, -0.002245, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.005951, -0.001661, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004751, -0.001111, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003546, -0.000603, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.002319, -0.00015, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.001109, 0.000222, 0.0381)
boolstatus = Part.InsertCurveFilePoint(6.7e-05, 0.000513, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001192, 0.000722, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.002248, 0.000854, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003218, 0.000914, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00409, 0.00091, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004849, 0.00085, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005485, 0.000743, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00599, 0.000598, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006357, 0.000422, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006583, 0.000221, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00661, -0.00023, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006415, -0.000457, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006086, -0.000681, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00563, -0.000904, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005056, -0.001128, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004373, -0.001353, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003591, -0.001584, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.002721, -0.001824, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001773, -0.002077, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.000758, -0.002348, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.000311, -0.002641, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.001424, -0.002962, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.002569, -0.003314, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003763, -0.003699, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004973, -0.004094, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.006184, -0.004497, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007382, -0.004907, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008555, -0.005318, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009688, -0.005728, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01077, -0.006131, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011789, -0.006521, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.012734, -0.006892, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.013594, -0.007238, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014361, -0.007552, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015024, -0.007829, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015578, -0.008063, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.016016, -0.00825, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.016604, -0.00847, 0.0381)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.022909, -0.010642, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.02231, -0.010115, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021832, -0.009741, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021223, -0.009275, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020486, -0.008725, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.019626, -0.008102, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.018649, -0.007419, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.017564, -0.006687, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016378, -0.005922, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015103, -0.005135, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01375, -0.004341, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012332, -0.003554, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.010862, -0.002786, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009356, -0.00205, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.007831, -0.001357, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.006298, -0.000718, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.004739, -0.000149, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003201, 0.000318, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.001707, 0.000681, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.000279, 0.000942, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.001062, 0.001104, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002294, 0.001176, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.0034, 0.001167, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004364, 0.001087, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00517, 0.000949, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00581, 0.000762, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006276, 0.000537, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006562, 0.000281, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006594, -0.000291, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006344, -0.000578, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005926, -0.000862, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005346, -0.001143, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004617, -0.001424, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.003749, -0.001707, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002756, -0.001997, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00165, -0.002297, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.000445, -0.002613, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.000843, -0.002952, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.002202, -0.00332, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003616, -0.003722, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.005071, -0.004163, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.004646, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.008126, -0.005142, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009665, -0.005648, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.011188, -0.006162, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012678, -0.006679, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.014118, -0.007194, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015493, -0.0077, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016789, -0.008191, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01799, -0.008657, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.019083, -0.009092, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020057, -0.009487, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020901, -0.009836, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021605, -0.01013, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.022161, -0.010365, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.022909, -0.010642, 0.05715)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.025519, -0.008685, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024841, -0.008179, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024303, -0.007825, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.023619, -0.007385, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.022792, -0.006868, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.021828, -0.006284, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.020737, -0.005646, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.019526, -0.004968, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018206, -0.004261, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.016791, -0.00354, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015292, -0.002818, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.013724, -0.002109, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.012104, -0.001425, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.010448, -0.000777, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.008776, -0.000177, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.0071, 0.000366, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.005403, 0.000832, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.003737, 0.001192, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.002126, 0.001446, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.000594, 0.001598, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.000838, 0.001653, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.002147, 0.001622, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003315, 0.001517, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004326, 0.001349, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005167, 0.001132, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005828, 0.00088, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.0063, 0.000601, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.00658, 0.000306, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006564, -0.000301, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006276, -0.000583, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005809, -0.000847, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005172, -0.001094, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004377, -0.001327, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003435, -0.001551, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.002359, -0.001771, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.001164, -0.001993, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.000136, -0.002223, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.001528, -0.00247, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.002996, -0.00274, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.004525, -0.003042, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.006101, -0.003382, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.007747, -0.003762, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.009416, -0.004153, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.011087, -0.004554, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.012741, -0.004965, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.014361, -0.005383, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015928, -0.005802, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017426, -0.006218, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018837, -0.006624, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.020147, -0.007013, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.021341, -0.007378, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.022405, -0.007711, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.023327, -0.008006, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024097, -0.008256, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024705, -0.008457, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.025519, -0.008685, 0.0762)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.024078, -0.006535, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.023414, -0.006093, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.02289, -0.005788, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.022223, -0.005409, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.021418, -0.004964, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.020481, -0.004463, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.019421, -0.003919, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018247, -0.003341, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016968, -0.002743, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.015598, -0.002137, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.01415, -0.001533, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.012638, -0.000946, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.011078, -0.000384, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.009486, 0.000141, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.007881, 0.00062, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.006276, 0.001046, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004654, 0.001399, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.003067, 0.001653, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.001538, 0.00181, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-8.7e-05, 0.001875, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.001263, 0.001854, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002494, 0.001758, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003589, 0.001599, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.004532, 0.001389, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005313, 0.001143, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005922, 0.000871, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006352, 0.000585, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006601, 0.000293, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006555, -0.000278, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006269, -0.000529, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005816, -0.000753, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005204, -0.000954, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.004443, -0.001133, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003545, -0.001296, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002521, -0.001448, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.001385, -0.001595, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.000149, -0.001746, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.001174, -0.001907, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.00257, -0.002087, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004025, -0.002293, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.005526, -0.002533, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.007095, -0.002806, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.008687, -0.003089, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.01028, -0.003382, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.011858, -0.003685, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.013405, -0.003996, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.014902, -0.004311, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016333, -0.004626, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.017682, -0.004936, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018936, -0.005235, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.020078, -0.005518, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.021096, -0.005777, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.02198, -0.006008, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.022717, -0.006204, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.0233, -0.006362, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.024078, -0.006535, 0.09525)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.021473, -0.004962, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020856, -0.004582, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.02037, -0.004321, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.019752, -0.003997, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.019007, -0.003619, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01814, -0.003194, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.017159, -0.002733, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016074, -0.002245, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.014893, -0.001743, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01363, -0.001235, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.012295, -0.000733, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.010902, -0.000247, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.009467, 0.000214, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.008004, 0.000641, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.006531, 0.001025, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.005059, 0.001361, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.003574, 0.00163, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.002124, 0.001811, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.00073, 0.001905, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00059, 0.001918, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001816, 0.001856, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.002931, 0.00173, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003921, 0.00155, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004772, 0.00133, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005473, 0.001081, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006017, 0.000815, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006399, 0.000541, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006616, 0.000268, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006557, -0.000249, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006289, -0.000468, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00587, -0.000657, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005307, -0.00082, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00461, -0.000959, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003789, -0.001078, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.002854, -0.001184, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001817, -0.001282, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.000689, -0.001379, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.000517, -0.001484, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.001791, -0.001603, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.00312, -0.001744, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.004492, -0.001915, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.005926, -0.002113, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.00738, -0.00232, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.008837, -0.002535, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.010281, -0.00276, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.011695, -0.002993, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.013066, -0.003232, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.014376, -0.003473, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.015612, -0.003712, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01676, -0.003944, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.017807, -0.004165, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01874, -0.004368, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01955, -0.00455, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020226, -0.004705, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020761, -0.004829, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.021473, -0.004962, 0.1143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.018202, -0.003717, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01765, -0.003397, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.017217, -0.003179, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.016666, -0.002908, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.016001, -0.002592, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015229, -0.002238, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014356, -0.001855, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01339, -0.001451, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01234, -0.001036, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.011216, -0.000619, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010031, -0.000208, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.008794, 0.000188, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.007521, 0.00056, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.006225, 0.000902, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004919, 0.001206, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.003617, 0.001467, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.002304, 0.00167, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.001025, 0.001795, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000204, 0.001846, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001365, 0.001827, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002443, 0.001744, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003421, 0.001608, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004287, 0.001427, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.00503, 0.001214, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005642, 0.000979, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006114, 0.000732, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006444, 0.000482, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006629, 0.000237, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006564, -0.000217, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.006323, -0.000403, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005951, -0.00056, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005452, -0.00069, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004836, -0.000796, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004111, -0.000882, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003286, -0.000954, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002371, -0.001016, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001377, -0.001076, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000313, -0.00114, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.000811, -0.001215, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.001983, -0.001309, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.003193, -0.001427, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004459, -0.001569, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.005744, -0.001717, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.00703, -0.001873, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.008305, -0.002038, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.009555, -0.00221, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010766, -0.002389, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.011924, -0.00257, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013017, -0.002752, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014032, -0.00293, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014958, -0.0031, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015784, -0.003257, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.016501, -0.003398, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.017099, -0.003519, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.017573, -0.003617, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.018202, -0.003717, 0.13335)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.014131, -0.002554, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013664, -0.002299, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013299, -0.002127, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012834, -0.001913, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012273, -0.001665, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011622, -0.001387, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010886, -0.001087, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010073, -0.000771, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009189, -0.000449, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.008244, -0.000125, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007247, 0.000191, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.006209, 0.000494, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00514, 0.000776, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004053, 0.001032, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002959, 0.001257, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001868, 0.001447, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00077, 0.001587, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.000299, 0.001663, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001323, 0.001679, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00229, 0.001638, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003186, 0.001545, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003998, 0.00141, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004716, 0.001241, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00533, 0.001047, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.005834, 0.000838, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006223, 0.000622, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006492, 0.000407, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00664, 0.000198, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006577, -0.000178, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006372, -0.000328, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.006058, -0.000451, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00564, -0.000548, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.005124, -0.000623, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004518, -0.000679, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00383, -0.000721, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003066, -0.000753, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002237, -0.000781, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001349, -0.000811, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.000411, -0.000849, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.000567, -0.000902, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001578, -0.000974, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002636, -0.001064, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.003709, -0.00116, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004784, -0.001262, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00585, -0.001371, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.006895, -0.001487, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007908, -0.00161, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.008876, -0.001736, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009791, -0.001863, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.01064, -0.001989, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011415, -0.002111, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012107, -0.002224, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012707, -0.002326, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013208, -0.002413, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013605, -0.002484, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.014131, -0.002554, 0.1524)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.008494, -0.00154, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008151, -0.001362, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007883, -0.001242, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007541, -0.001094, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00713, -0.000922, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006652, -0.00073, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006113, -0.000523, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005516, -0.000306, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004869, -8.5e-05, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004177, 0.000136, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003447, 0.000351, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002688, 0.000555, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001906, 0.000744, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001111, 0.000914, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000313, 0.001061, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000483, 0.001182, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001284, 0.001267, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002062, 0.001307, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002807, 0.001302, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.00351, 0.001257, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.00416, 0.001177, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.004748, 0.001066, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.005267, 0.000932, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.005711, 0.000782, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006074, 0.000622, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006354, 0.000459, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006546, 0.000298, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006651, 0.000145, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006599, -0.000128, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006448, -0.000234, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.006217, -0.000319, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.005912, -0.000383, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.005536, -0.00043, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.005095, -0.000461, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.004593, -0.000481, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.004038, -0.000492, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.003434, -0.0005, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002788, -0.000509, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002106, -0.000522, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001393, -0.000546, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000657, -0.000583, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000113, -0.000632, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000895, -0.000685, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001678, -0.000743, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002455, -0.000806, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003217, -0.000875, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003955, -0.000948, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004661, -0.001025, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005328, -0.001104, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005948, -0.001183, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006513, -0.001259, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007018, -0.001331, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007455, -0.001396, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007821, -0.001452, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008111, -0.001497, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008494, -0.00154, 0.17145)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.000923, -0.000664, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000751, -0.000577, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000616, -0.00052, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000444, -0.000448, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000237, -0.000365, 0.1905)
boolstatus = Part.InsertCurveFilePoint(3.0e-06, -0.000272, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000274, -0.000172, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000574, -6.8e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000899, 3.8e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.001247, 0.000144, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.001613, 0.000246, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.001994, 0.000343, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.002386, 0.000432, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.002785, 0.000511, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.003185, 0.000579, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.003584, 0.000634, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.003985, 0.000671, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.004374, 0.000685, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.004747, 0.000678, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005098, 0.000651, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005422, 0.000606, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005715, 0.000546, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005974, 0.000476, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006195, 0.000397, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006375, 0.000315, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006514, 0.000232, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006609, 0.00015, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.00666, 7.2e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006632, -6.4e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006556, -0.000116, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.00644, -0.000156, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006287, -0.000186, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.006099, -0.000207, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005878, -0.00022, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005627, -0.000226, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005349, -0.000228, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.005047, -0.000227, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.004724, -0.000227, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.004383, -0.000229, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.004027, -0.000236, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.003659, -0.000249, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.003273, -0.000269, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.002882, -0.00029, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.00249, -0.000313, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.002101, -0.000339, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.00172, -0.000368, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.00135, -0.0004, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000997, -0.000433, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000663, -0.000468, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000352, -0.000503, 0.1905)
boolstatus = Part.InsertCurveFilePoint(6.9e-05, -0.000538, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000184, -0.00057, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000403, -0.000599, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000586, -0.000625, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000731, -0.000645, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000923, -0.000664, 0.1905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.007, -1.2246467991473531e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.007, -1.2246467991473531e-19, 0.01143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.00842419, -0.002121, 0.01905, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.01660399, -0.00847013, 0.0381, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.02290859, -0.01064222, 0.05715, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.025518939999999997, -0.00868457, 0.0762, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.024078119999999998, -0.006535180000000001, 0.09525, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.02147338, -0.004961999999999999, 0.1143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.01820229, -0.0037168199999999996, 0.13335, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.0141313, -0.00255377, 0.1524, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.008494479999999999, -0.0015401, 0.17145000000000002, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.0009234999999999997, -0.00066413, 0.1905, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
