Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.0125, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.012402, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.012118, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011676, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011118, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0105, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0084, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0063, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0042, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0021, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0021, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0042, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0063, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0084, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0105, 0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011118, 0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011676, 0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.012118, 0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.012402, 0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0125, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.012402, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.012118, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011676, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.011118, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0105, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0084, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0063, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0042, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0021, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0021, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0042, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0063, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0084, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0105, -0.002, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011118, -0.001902, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.011676, -0.001618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.012118, -0.001176, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.012402, -0.000618, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0125, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.0125, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.012402, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.012118, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011676, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011118, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0105, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0084, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0063, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0042, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0021, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0021, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0042, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0063, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0084, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0105, 0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011118, 0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011676, 0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.012118, 0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.012402, 0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0125, 0.0, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.012402, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.012118, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011676, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.011118, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0105, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0084, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0063, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0042, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0021, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0021, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0042, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0063, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0084, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0105, -0.002, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011118, -0.001902, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.011676, -0.001618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.012118, -0.001176, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.012402, -0.000618, 0.0198)
boolstatus = Part.InsertCurveFilePoint(-0.0125, 0.0, 0.0198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.014329, -0.003674, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.013751, -0.00331, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.013297, -0.003063, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.01272, -0.002758, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.012024, -0.002402, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.011214, -0.002004, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.010299, -0.001574, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009286, -0.001123, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.008185, -0.000661, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007007, -0.000198, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005763, 0.000256, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.004466, 0.000689, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.00313, 0.001094, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001768, 0.001461, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.000397, 0.001784, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000971, 0.002056, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002351, 0.002257, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003697, 0.002368, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.00499, 0.002392, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006213, 0.002334, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007348, 0.002203, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008379, 0.002011, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009293, 0.00177, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010078, 0.001494, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010724, 0.001195, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011224, 0.000888, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011574, 0.000581, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.01177, 0.000283, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011814, 0.0, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011707, -0.000255, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011456, -0.000469, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.011065, -0.000645, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.010542, -0.000784, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009894, -0.000892, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.009132, -0.000973, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.008264, -0.001033, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.007302, -0.00108, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.006255, -0.001121, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.005136, -0.001165, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.003954, -0.001221, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.002721, -0.001297, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.001448, -0.001402, 0.033)
boolstatus = Part.InsertCurveFilePoint(0.000117, -0.001532, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.001234, -0.00167, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.002587, -0.001817, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.003928, -0.001974, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.005242, -0.002142, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.006514, -0.002317, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.007732, -0.002499, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.00888, -0.002682, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.009947, -0.002864, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.01092, -0.003038, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.011788, -0.0032, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.012541, -0.003347, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.01317, -0.003472, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.013667, -0.003574, 0.033)
boolstatus = Part.InsertCurveFilePoint(-0.014329, -0.003674, 0.033)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.02873, -0.014673, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.027916, -0.013949, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.027266, -0.013438, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.026436, -0.012798, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.025433, -0.012044, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.024262, -0.011189, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.022933, -0.010252, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.021455, -0.009248, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.01984, -0.008197, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018104, -0.007117, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.016262, -0.006027, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.01433, -0.004945, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012328, -0.00389, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.010277, -0.002878, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008198, -0.001925, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006109, -0.001045, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.003984, -0.00026, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.001887, 0.000385, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00015, 0.000888, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002098, 0.001251, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003926, 0.001479, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005608, 0.001583, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007118, 0.001576, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008433, 0.001472, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009535, 0.001287, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010409, 0.001036, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011045, 0.000731, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011437, 0.000383, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011583, 0.0, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011484, -0.000398, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.011145, -0.000791, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010575, -0.00118, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.009786, -0.001567, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008792, -0.001954, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007609, -0.002344, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.006254, -0.002744, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.004746, -0.00316, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003104, -0.003598, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.001347, -0.004067, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.000506, -0.004575, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.002433, -0.005131, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.004416, -0.00574, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.006485, -0.006407, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.008582, -0.007092, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.01068, -0.007791, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.012755, -0.0085, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.014786, -0.009213, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.01675, -0.009923, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.018624, -0.010621, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.020389, -0.011296, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.022026, -0.011939, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.023516, -0.012538, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.024844, -0.013082, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.025994, -0.013562, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.026953, -0.013967, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.027711, -0.014291, 0.066)
boolstatus = Part.InsertCurveFilePoint(-0.02873, -0.014673, 0.066)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.039684, -0.018435, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.038647, -0.017521, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.03782, -0.016875, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.036764, -0.016066, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.035487, -0.015114, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.033997, -0.014035, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.032306, -0.012851, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.030425, -0.011584, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.028372, -0.010258, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026163, -0.008895, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.023819, -0.00752, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.021362, -0.006156, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.018817, -0.004826, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.016208, -0.003551, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.013565, -0.002351, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.010911, -0.001244, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008209, -0.000258, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.005545, 0.000552, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.002957, 0.00118, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.000483, 0.001632, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.001839, 0.001913, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.003974, 0.002037, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00589, 0.002021, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007559, 0.001883, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.008957, 0.001643, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010065, 0.00132, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010871, 0.00093, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011367, 0.000487, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01155, 0.0, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011422, -0.000504, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.01099, -0.001002, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.010265, -0.001493, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009262, -0.00198, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007998, -0.002467, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.006495, -0.002957, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.004773, -0.003459, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002858, -0.003978, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.000772, -0.004527, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.001461, -0.005114, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.003815, -0.005751, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.006264, -0.006447, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.008784, -0.007211, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.011412, -0.008048, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.014077, -0.008908, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.016743, -0.009785, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.01938, -0.010675, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.021961, -0.01157, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.024457, -0.012463, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.026839, -0.013339, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.029083, -0.014188, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.031163, -0.014997, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.033057, -0.01575, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.034745, -0.016435, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.036206, -0.017038, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.037426, -0.017548, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.03839, -0.017956, 0.099)
boolstatus = Part.InsertCurveFilePoint(-0.039684, -0.018435, 0.099)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.044239, -0.015044, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.043064, -0.014168, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.042133, -0.013556, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.040947, -0.012793, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.039515, -0.011897, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.037846, -0.010886, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.035955, -0.009781, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.033858, -0.008605, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.031572, -0.007381, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.029119, -0.006132, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.026522, -0.004882, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.023807, -0.003653, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.021001, -0.002468, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.018133, -0.001346, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.015235, -0.000307, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.012333, 0.000633, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.009392, 0.001441, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.006506, 0.002065, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.003716, 0.002505, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.001061, 0.002768, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.001418, 0.002864, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003686, 0.00281, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005709, 0.002627, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.007461, 0.002337, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008918, 0.001962, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010062, 0.001524, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.01088, 0.001042, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011366, 0.00053, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011517, 0.0, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.011338, -0.000522, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010839, -0.00101, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010029, -0.001467, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008926, -0.001895, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.007548, -0.002299, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.005917, -0.002687, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.004054, -0.003068, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.001984, -0.003452, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.000269, -0.003851, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.00268, -0.004278, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.005223, -0.004746, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.007872, -0.00527, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.010602, -0.005859, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.013453, -0.006516, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.016344, -0.007193, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.019238, -0.007889, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.022104, -0.008601, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.02491, -0.009324, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.027625, -0.010051, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.030219, -0.010771, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.032664, -0.011474, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.034934, -0.012149, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.037001, -0.01278, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.038844, -0.013358, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.040442, -0.013869, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.041775, -0.014302, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.042829, -0.014649, 0.132)
boolstatus = Part.InsertCurveFilePoint(-0.044239, -0.015044, 0.132)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.041974, -0.011321, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.040823, -0.010556, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.039916, -0.010027, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.03876, -0.00937, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.037366, -0.008599, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.035743, -0.007732, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.033907, -0.006788, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.031872, -0.005788, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.029657, -0.004752, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.027285, -0.003701, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.024776, -0.002656, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.022157, -0.001638, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.019455, -0.000665, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.016697, 0.000244, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.013916, 0.001075, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.011136, 0.001812, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.008326, 0.002423, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.005577, 0.002864, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002927, 0.003136, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.000415, 0.003248, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.001924, 0.003211, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.004056, 0.003045, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005952, 0.00277, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.007587, 0.002407, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.008939, 0.001979, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009994, 0.001509, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010739, 0.001013, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.01117, 0.000507, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011286, 0.0, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011091, -0.000482, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.010596, -0.000917, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.00981, -0.001305, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.00875, -0.001652, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.007432, -0.001962, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005877, -0.002245, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.004103, -0.002508, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.002135, -0.002764, 0.165)
boolstatus = Part.InsertCurveFilePoint(-7.0e-06, -0.003024, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.002298, -0.003304, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.004716, -0.003615, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.007237, -0.003973, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.009837, -0.004389, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.012555, -0.004862, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.015312, -0.005352, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.018072, -0.005859, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.020806, -0.006384, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.023484, -0.006921, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.026078, -0.007467, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.028557, -0.008013, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.030895, -0.00855, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.033066, -0.009069, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.035044, -0.009558, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.036809, -0.010008, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.038339, -0.010408, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.039617, -0.010748, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.040627, -0.011021, 0.165)
boolstatus = Part.InsertCurveFilePoint(-0.041974, -0.011321, 0.165)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.038089, -0.008596, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.037019, -0.007937, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.036178, -0.007486, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.035107, -0.006925, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.033816, -0.006269, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.032314, -0.005533, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.030616, -0.004734, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.028735, -0.003889, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.02669, -0.003019, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.024501, -0.002139, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.022189, -0.001269, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.019777, -0.000427, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.017291, 0.000371, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.014757, 0.00111, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.012204, 0.001776, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.009655, 0.002358, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.007082, 0.002823, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.004571, 0.003137, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.002155, 0.0033, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.000131, 0.003322, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.002255, 0.003215, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.004187, 0.002996, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005901, 0.002686, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007375, 0.002304, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00859, 0.001873, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009533, 0.001412, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010195, 0.000938, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.01057, 0.000464, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010659, 0.0, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010467, -0.000432, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.010003, -0.000811, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.009277, -0.001139, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.008303, -0.00142, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007096, -0.001661, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.005673, -0.001868, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.004054, -0.002051, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.002257, -0.00222, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.000303, -0.002389, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.001787, -0.002571, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.003994, -0.002777, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.006296, -0.003022, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.008672, -0.003317, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.011156, -0.003661, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.013676, -0.004018, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.016199, -0.004392, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.0187, -0.004782, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.021151, -0.005185, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.023524, -0.005599, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.025794, -0.006016, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.027935, -0.00643, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.029924, -0.006833, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.031737, -0.007214, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.033355, -0.007567, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.034757, -0.007881, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.035929, -0.00815, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.036855, -0.008366, 0.198)
boolstatus = Part.InsertCurveFilePoint(-0.038089, -0.008596, 0.198)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.033644, -0.006439, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.032687, -0.005884, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.031937, -0.005506, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.030982, -0.005037, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.029831, -0.00449, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.028493, -0.003877, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.02698, -0.003213, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.025307, -0.002514, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.023488, -0.001795, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.021542, -0.001072, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.019488, -0.00036, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.017346, 0.000325, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.015141, 0.00097, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.012895, 0.001562, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.010634, 0.002089, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.008378, 0.002542, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.006104, 0.002892, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003887, 0.00311, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.001758, 0.003198, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.000253, 0.003165, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.002119, 0.003022, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.003814, 0.002785, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005314, 0.002472, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006602, 0.002102, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007661, 0.001695, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00848, 0.001268, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009051, 0.000836, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00937, 0.000411, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009438, 0.0, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.009259, -0.000376, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008842, -0.000698, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.008196, -0.00097, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007333, -0.001195, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006265, -0.001379, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.005009, -0.001528, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.00358, -0.001652, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.001996, -0.00176, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.000273, -0.001863, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.00157, -0.001975, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.003516, -0.002105, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.005547, -0.002268, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.007643, -0.002473, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.009837, -0.002718, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.012062, -0.002974, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.014291, -0.003245, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.016499, -0.00353, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.018665, -0.003829, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.020762, -0.004138, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.022768, -0.004453, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.024661, -0.004767, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.02642, -0.005076, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.028024, -0.00537, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.029455, -0.005643, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.030696, -0.005887, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.031733, -0.006096, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.032553, -0.006265, 0.231)
boolstatus = Part.InsertCurveFilePoint(-0.033644, -0.006439, 0.231)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.028604, -0.004424, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.027795, -0.003983, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.027162, -0.003684, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.026356, -0.003315, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.025386, -0.002884, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.024258, -0.002402, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022983, -0.001882, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.021574, -0.001336, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.020043, -0.000777, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.018406, -0.000217, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.016679, 0.000331, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.014881, 0.000855, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.013029, 0.001344, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.011145, 0.001788, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00925, 0.002178, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.007361, 0.002506, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005459, 0.002749, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003608, 0.002882, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.001832, 0.002908, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.000157, 0.002837, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.001394, 0.002677, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.0028, 0.002442, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004044, 0.002149, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005108, 0.001813, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005981, 0.001451, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006655, 0.001077, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007121, 0.000705, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007378, 0.000343, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007425, 0.0, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007268, -0.000309, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006913, -0.000569, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.006369, -0.000781, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.005645, -0.00095, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004752, -0.001079, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.003702, -0.001176, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.002509, -0.001248, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.001187, -0.001304, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.00025, -0.001352, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.001788, -0.001405, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.003413, -0.001471, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.005108, -0.001562, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.006859, -0.001687, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.008691, -0.001843, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.01055, -0.002009, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.012413, -0.002186, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.014259, -0.002375, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.016069, -0.002576, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.017823, -0.002788, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.019501, -0.003007, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.021085, -0.003227, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.022557, -0.003446, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.0239, -0.003656, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.025098, -0.003852, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.026137, -0.004029, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.027005, -0.00418, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.027692, -0.004303, 0.264)
boolstatus = Part.InsertCurveFilePoint(-0.028604, -0.004424, 0.264)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.021843, -0.002668, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.021248, -0.002359, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020783, -0.002152, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020191, -0.001896, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019479, -0.001597, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.018651, -0.001264, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017717, -0.000906, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016684, -0.00053, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.015562, -0.000147, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.014363, 0.000236, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.0131, 0.000608, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011784, 0.000962, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.01043, 0.001289, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.009053, 0.001583, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.007669, 0.001838, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.006291, 0.002048, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004904, 0.002195, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003556, 0.002263, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002265, 0.002256, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.001048, 0.002178, 0.297)
boolstatus = Part.InsertCurveFilePoint(7.7e-05, 0.002038, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001097, 0.001846, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001996, 0.001614, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002765, 0.001354, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003394, 0.001077, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003878, 0.000795, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004212, 0.000517, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004393, 0.00025, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004422, 0.0, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004303, -0.000222, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.004041, -0.000406, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003642, -0.000552, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003113, -0.000663, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.002462, -0.000744, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.001697, -0.000799, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.000828, -0.000833, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.000134, -0.000853, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00118, -0.000866, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.002299, -0.000881, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.003481, -0.000905, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.004714, -0.000945, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.00599, -0.001009, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.007324, -0.001095, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.008679, -0.001187, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.010036, -0.001287, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.011381, -0.001397, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.0127, -0.001516, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.013979, -0.001643, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.015202, -0.001776, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.016357, -0.001912, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.017431, -0.002049, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.01841, -0.002181, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.019284, -0.002306, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020043, -0.002418, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.020676, -0.002515, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.021178, -0.002594, 0.297)
boolstatus = Part.InsertCurveFilePoint(-0.021843, -0.002668, 0.297)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.012919, -0.00115, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012619, -0.001, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012385, -0.0009, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012088, -0.000776, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011729, -0.000632, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011313, -0.000471, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010844, -0.000298, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010325, -0.000118, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009761, 6.6e-05, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009159, 0.000249, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.008525, 0.000426, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007864, 0.000594, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007185, 0.000748, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006495, 0.000886, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005801, 0.001003, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005111, 0.001098, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004416, 0.001162, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003742, 0.001187, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003096, 0.001174, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002489, 0.001127, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001927, 0.001049, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001419, 0.000946, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000971, 0.000824, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000588, 0.000688, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000275, 0.000546, 0.33)
boolstatus = Part.InsertCurveFilePoint(-3.5e-05, 0.000401, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000129, 0.00026, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000218, 0.000125, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.000231, 0.0, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.00017, -0.00011, 0.33)
boolstatus = Part.InsertCurveFilePoint(3.8e-05, -0.0002, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000163, -0.00027, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000428, -0.000323, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.000754, -0.000358, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001137, -0.00038, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.001571, -0.000391, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002053, -0.000395, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.002576, -0.000394, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003135, -0.000394, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.003726, -0.000397, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004343, -0.000409, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.004981, -0.000432, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.005649, -0.000465, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.006327, -0.000502, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007006, -0.000543, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.007679, -0.000588, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00834, -0.000638, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.00898, -0.000693, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.009593, -0.000751, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010171, -0.000811, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.010709, -0.000872, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011199, -0.000931, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.011637, -0.000987, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012017, -0.001038, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012335, -0.001082, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012586, -0.001118, 0.33)
boolstatus = Part.InsertCurveFilePoint(-0.012919, -0.00115, 0.33)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.0125, -2.4492935982947063e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.0125, -2.4492935982947063e-19, 0.0198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.01432908, -0.00367417, 0.033, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.028729809999999998, -0.01467266, 0.066, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.03968418, -0.01843534, 0.099, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.04423904, -0.015044140000000001, 0.132, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.04197414, -0.01132079, 0.165, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.03808898, -0.00859558, 0.198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.03364353, -0.00643858, 0.23099999999999998, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.028604429999999997, -0.00442386, 0.264, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.021842849999999997, -0.00266789, 0.297, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.012918769999999994, -0.00115046, 0.33, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
