Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.001404, 0.000914, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.00251, 0.001545, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.003918, 0.002328, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.005617, 0.003246, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.007594, 0.004279, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.00983, 0.005402, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.012308, 0.006591, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.015004, 0.007821, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.017892, 0.009067, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.020944, 0.010305, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.02413, 0.011509, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.027417, 0.012658, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.03077, 0.013729, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.03415, 0.014703, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.037528, 0.015565, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.040941, 0.016273, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.044278, 0.016776, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.047493, 0.017075, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.050539, 0.017182, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.053374, 0.017112, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.055956, 0.016886, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.058251, 0.01653, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.060228, 0.016072, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.061863, 0.015538, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.063136, 0.014956, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.064033, 0.014347, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.06455, 0.013728, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.064684, 0.013112, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.064443, 0.01253, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.063837, 0.012009, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.062881, 0.011547, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.061592, 0.011139, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.059991, 0.010778, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.058103, 0.010453, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.05595, 0.010154, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.053561, 0.009867, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.050962, 0.009576, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.048182, 0.009263, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.045247, 0.008913, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.042188, 0.008509, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.039031, 0.008035, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.035732, 0.007492, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.032385, 0.00693, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.029034, 0.006346, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.025714, 0.005742, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.022461, 0.005121, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.019312, 0.004489, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.0163, 0.003856, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.013461, 0.003232, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.010823, 0.002627, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.00842, 0.002057, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.006276, 0.001532, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.004417, 0.001065, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.002864, 0.000667, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.001637, 0.000348, 0.0495)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.0495)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.001923, 0.001385, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.003444, 0.002349, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.005382, 0.003549, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.007721, 0.004959, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.010446, 0.006549, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.013531, 0.008283, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.016953, 0.010127, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.020681, 0.012044, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.024679, 0.013997, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.02891, 0.015948, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.033332, 0.01786, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.0379, 0.019701, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.042566, 0.021436, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.047277, 0.023037, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.051993, 0.024479, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.056769, 0.025705, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.061451, 0.026637, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.065972, 0.027272, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.070269, 0.027626, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.074279, 0.027714, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.077943, 0.027566, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.081209, 0.027215, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.084033, 0.026698, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.086378, 0.026053, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.088215, 0.025314, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.089524, 0.024513, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.090295, 0.023673, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.090525, 0.022812, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.090223, 0.021973, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.089401, 0.021197, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.088081, 0.020481, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.086287, 0.019819, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.084049, 0.019202, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.081402, 0.018619, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.07838, 0.018054, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.075023, 0.01749, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.071371, 0.016906, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.067464, 0.01628, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.06334, 0.015592, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.059044, 0.014817, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.054616, 0.013938, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.04999, 0.012953, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.045298, 0.011937, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.040602, 0.01089, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.035951, 0.009816, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.031396, 0.008723, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.026988, 0.007622, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.022776, 0.006528, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.018805, 0.005458, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.015119, 0.004429, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.01176, 0.003464, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.008765, 0.00258, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.00617, 0.001797, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.004003, 0.001133, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.002289, 0.0006, 0.066)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.066)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.0024, 0.001905, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.004306, 0.003242, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.006736, 0.00491, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.009672, 0.006873, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.013095, 0.009091, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.016975, 0.011518, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.021283, 0.014107, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.025982, 0.016809, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.031028, 0.019573, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.036374, 0.022349, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.04197, 0.025087, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.047758, 0.027741, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.05368, 0.030264, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.059668, 0.032618, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.065672, 0.034766, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.071766, 0.036639, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.077757, 0.038125, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.083558, 0.039221, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.089087, 0.039937, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.094261, 0.040294, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.099002, 0.040324, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.103242, 0.040069, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.106921, 0.039573, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.109988, 0.038881, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.112405, 0.038038, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.114145, 0.037083, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.115191, 0.036045, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.115541, 0.034946, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.115201, 0.033845, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.114187, 0.032793, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.112525, 0.031788, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.110248, 0.030824, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.107395, 0.029892, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.104011, 0.028978, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.100142, 0.028065, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.095841, 0.027134, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.09116, 0.026158, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.08615, 0.025113, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.080866, 0.023974, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.075365, 0.022714, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.069698, 0.02131, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.063782, 0.019758, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.057785, 0.018161, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.051782, 0.016525, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.04584, 0.014856, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.040024, 0.013169, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.034397, 0.011479, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.029022, 0.009811, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.023958, 0.008188, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.019259, 0.006636, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.01498, 0.005186, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.011165, 0.003864, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.00786, 0.002695, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.005101, 0.001706, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.002921, 0.000914, 0.0825)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.0825)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.002831, 0.002472, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.00509, 0.00422, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.007971, 0.006403, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.011456, 0.008977, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.015523, 0.011891, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.020138, 0.015088, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.025267, 0.018508, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.03087, 0.022088, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.036893, 0.025765, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.043284, 0.029474, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.049983, 0.03315, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.056923, 0.036734, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.064034, 0.040166, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.071236, 0.043394, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.078469, 0.04637, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.085828, 0.049016, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.093083, 0.051181, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.100128, 0.052857, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.106861, 0.054052, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.11318, 0.054786, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.118988, 0.055096, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.124198, 0.055027, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.128734, 0.05463, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.132531, 0.053959, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.135542, 0.053065, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.137728, 0.051994, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.13907, 0.050783, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.139562, 0.049457, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.139208, 0.048087, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.138027, 0.04674, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.136048, 0.045414, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.133313, 0.044102, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.12987, 0.042796, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.125777, 0.041482, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.121089, 0.040141, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.115872, 0.038753, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.110193, 0.037288, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.104115, 0.03572, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.097706, 0.034021, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.091037, 0.032161, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.084175, 0.030115, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.077016, 0.027873, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.069758, 0.025572, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.062498, 0.023222, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.055313, 0.020836, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.048283, 0.018434, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.041486, 0.016041, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.034996, 0.013688, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.028884, 0.011409, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.023216, 0.009237, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.018056, 0.007215, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.013458, 0.005376, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.009476, 0.003754, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.006152, 0.002383, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.003526, 0.001287, 0.099)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.099)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.003213, 0.003083, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.005789, 0.005276, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.009078, 0.00802, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.01306, 0.011259, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.01771, 0.014934, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.022995, 0.018973, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.028876, 0.023306, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.035307, 0.027853, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.042232, 0.032539, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.049589, 0.037282, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.057313, 0.042005, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.065327, 0.046631, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.073552, 0.051088, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.081896, 0.055308, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.090291, 0.059231, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.098853, 0.06277, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.107319, 0.065736, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.115564, 0.068109, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.123466, 0.069898, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.130903, 0.071117, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.137759, 0.071806, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.143928, 0.072014, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.149318, 0.071796, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.15385, 0.071212, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.157462, 0.070322, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.160109, 0.069175, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.161764, 0.067816, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.16242, 0.066274, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.162078, 0.064634, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.160754, 0.062974, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.158486, 0.061295, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.155322, 0.05959, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.15132, 0.057854, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.146549, 0.056072, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.141075, 0.054224, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.134979, 0.052292, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.128339, 0.050244, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.121232, 0.048051, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.113742, 0.045684, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.105953, 0.043112, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.097945, 0.040311, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.089597, 0.037261, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.081137, 0.034134, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.072675, 0.03095, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.064304, 0.027728, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.056118, 0.024496, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.048206, 0.021286, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.040657, 0.018141, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.03355, 0.015105, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.026963, 0.01222, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.020968, 0.009541, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.015629, 0.007109, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.011006, 0.004968, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.007149, 0.003161, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.004101, 0.001719, 0.1155)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1155)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.003544, 0.003733, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.006399, 0.006406, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.010048, 0.009752, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.01447, 0.013708, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.019641, 0.018203, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.025524, 0.023153, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.03208, 0.028474, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.03926, 0.034073, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.047002, 0.039858, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.055241, 0.045734, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.063904, 0.051605, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.072907, 0.057381, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.082162, 0.062972, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.091569, 0.068296, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.10105, 0.073281, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.110744, 0.077831, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.120359, 0.081714, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.12975, 0.084901, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.138778, 0.087394, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.147299, 0.089204, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.155179, 0.090371, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.162291, 0.090945, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.168527, 0.090985, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.173791, 0.090556, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.17801, 0.089724, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.181128, 0.088543, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.183113, 0.087063, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.183954, 0.085319, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.183647, 0.083406, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.182209, 0.081418, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.179681, 0.079356, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.176119, 0.077217, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.171593, 0.074995, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.166181, 0.072679, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.15996, 0.07025, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.153025, 0.067688, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.145469, 0.064963, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.137382, 0.062046, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.128862, 0.058908, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.120007, 0.055517, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.110912, 0.051848, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.101438, 0.047875, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.091838, 0.043807, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.08224, 0.039672, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.072749, 0.035498, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.063471, 0.031323, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.05451, 0.027189, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.045963, 0.023149, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.037921, 0.019258, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.030472, 0.01557, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.023695, 0.012152, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.017661, 0.009054, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.012439, 0.006333, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.008083, 0.004037, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.004643, 0.002207, 0.132)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.132)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.003819, 0.004421, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.006914, 0.007602, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.010873, 0.01159, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.015676, 0.016309, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.021299, 0.02168, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.027705, 0.027604, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.034854, 0.033985, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.042696, 0.040714, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.051165, 0.047684, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.060193, 0.054783, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.069702, 0.061899, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.079601, 0.068925, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.089797, 0.075756, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.100177, 0.082292, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.110661, 0.088447, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.121409, 0.094121, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.132102, 0.099033, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.14258, 0.103146, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.152681, 0.106451, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.162245, 0.108957, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.171116, 0.110698, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.179148, 0.111727, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.186215, 0.112104, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.192205, 0.111898, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.197033, 0.111178, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.200631, 0.110006, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.20296, 0.108434, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.204005, 0.1065, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.203759, 0.104316, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.202235, 0.101986, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.199478, 0.099513, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.195555, 0.096899, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.190542, 0.094139, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.184529, 0.091226, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.177606, 0.088142, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.16988, 0.084869, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.161458, 0.081379, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.152446, 0.077642, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.142954, 0.073632, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.133096, 0.069316, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.122981, 0.064674, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.112452, 0.059666, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.101785, 0.054543, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.091123, 0.049346, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.080586, 0.04411, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.07029, 0.038883, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.06035, 0.03372, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.050876, 0.028686, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.041966, 0.023847, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.033717, 0.019271, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.026216, 0.015036, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.019541, 0.011203, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.013765, 0.00784, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.008949, 0.005007, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.005146, 0.002749, 0.1485)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1485)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.004036, 0.005141, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.007329, 0.008859, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.011545, 0.013523, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.016665, 0.019049, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.022668, 0.025346, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.029517, 0.032304, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.037173, 0.039809, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.045586, 0.047741, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.054686, 0.055975, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.064403, 0.064382, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.074658, 0.072834, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.085353, 0.081205, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.09639, 0.089374, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.10765, 0.097223, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.119044, 0.104652, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.130759, 0.111556, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.142452, 0.117606, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.153947, 0.122751, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.165064, 0.126976, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.175622, 0.130277, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.185445, 0.132688, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.194368, 0.134259, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.202247, 0.135051, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.208952, 0.135134, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.214386, 0.134583, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.218468, 0.133461, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.221153, 0.131826, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.222423, 0.12972, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.222263, 0.127266, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.220681, 0.124581, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.21773, 0.121674, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.213482, 0.118547, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.208024, 0.115199, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.201456, 0.111628, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.19388, 0.107818, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.185417, 0.103756, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.176188, 0.099413, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.166311, 0.094765, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.155912, 0.089785, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.145121, 0.084446, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.134059, 0.078727, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.122554, 0.072578, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.1109, 0.066294, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.099257, 0.059927, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.087754, 0.053522, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.076521, 0.047141, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.065683, 0.04085, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.055358, 0.034726, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.045653, 0.028852, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.036673, 0.023305, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.028512, 0.018178, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.021252, 0.013545, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.014974, 0.009484, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.009739, 0.006065, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.005607, 0.003342, 0.165)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.165)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.004194, 0.00589, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.00764, 0.010169, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.012057, 0.015542, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.017428, 0.021913, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.023736, 0.029183, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.030944, 0.037226, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.039015, 0.045916, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.0479, 0.055117, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.057529, 0.064687, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.067831, 0.074481, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.078725, 0.084351, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.09011, 0.094156, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.101883, 0.103755, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.113918, 0.113011, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.126124, 0.121811, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.138712, 0.130047, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.15132, 0.137339, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.163756, 0.14362, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.175821, 0.148864, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.187317, 0.153059, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.198046, 0.156233, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.207825, 0.158431, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.21649, 0.159713, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.223896, 0.160153, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.229929, 0.159826, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.234497, 0.158798, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.23755, 0.15713, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.239062, 0.154869, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.239012, 0.152148, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.237403, 0.1491, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.234292, 0.145734, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.22976, 0.142058, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.223902, 0.138077, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.21683, 0.13379, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.208656, 0.129188, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.199515, 0.12426, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.189541, 0.118983, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.178868, 0.113335, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.167635, 0.107293, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.155987, 0.100834, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.144059, 0.093942, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.131664, 0.08655, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.119112, 0.079003, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.106576, 0.071363, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.094197, 0.06369, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.082115, 0.056057, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.070465, 0.048543, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.059372, 0.041242, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.048953, 0.034248, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.039317, 0.027653, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.030564, 0.021565, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.022782, 0.016069, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.016055, 0.011256, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.010448, 0.007206, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.006023, 0.003983, 0.1815)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.1815)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.004289, 0.006664, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.007842, 0.011525, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.012402, 0.017635, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.017956, 0.024886, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.024489, 0.033169, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.031967, 0.042344, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.040358, 0.052273, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.049613, 0.062802, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.059663, 0.073775, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.070441, 0.085026, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.081861, 0.096392, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.093822, 0.107712, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.106218, 0.118825, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.11892, 0.129577, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.131831, 0.139837, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.14519, 0.1495, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.15862, 0.158132, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.171912, 0.165647, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.184853, 0.172007, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.197223, 0.177191, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.208807, 0.181216, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.219401, 0.184124, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.228822, 0.185973, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.236907, 0.186835, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.243529, 0.186786, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.248584, 0.185895, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.252011, 0.184226, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.253783, 0.181828, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.253868, 0.178847, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.252263, 0.175427, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.24903, 0.171582, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.244257, 0.167325, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.238048, 0.162665, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.230525, 0.157609, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.221812, 0.152151, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.212057, 0.146286, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.201408, 0.139997, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.190012, 0.133265, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.178024, 0.126074, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.165603, 0.118404, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.152898, 0.110246, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.139707, 0.101517, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.126353, 0.092609, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.11302, 0.083602, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.099861, 0.074566, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.087025, 0.065588, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.074655, 0.056764, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.062885, 0.048201, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.051837, 0.040009, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.041626, 0.032293, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.032356, 0.025179, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.024118, 0.018762, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.017, 0.013147, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.011069, 0.008426, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.00639, 0.00467, 0.198)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.198)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.00432, 0.007458, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.007933, 0.012921, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.012576, 0.01979, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.01824, 0.027952, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.024915, 0.037283, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.032573, 0.047633, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.041183, 0.058847, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.050701, 0.070758, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.061062, 0.083191, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.072197, 0.095963, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.084026, 0.108893, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.096444, 0.1218, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.109345, 0.134505, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.122597, 0.146834, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.136102, 0.158639, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.150123, 0.169818, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.164273, 0.179879, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.178332, 0.188721, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.192067, 0.19629, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.205242, 0.202552, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.217622, 0.207515, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.228984, 0.211214, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.239125, 0.213703, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.247865, 0.215051, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.255061, 0.215336, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.260598, 0.214625, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.264407, 0.212986, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.266454, 0.210471, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.266698, 0.207237, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.265129, 0.20344, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.261812, 0.199098, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.256843, 0.19423, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.250335, 0.188851, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.242419, 0.182975, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.233232, 0.1766, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.222932, 0.169732, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.211683, 0.162357, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.199646, 0.154463, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.186988, 0.146039, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.173884, 0.137073, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.160497, 0.127563, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.14661, 0.117408, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.132555, 0.10705, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.118529, 0.096585, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.104693, 0.086098, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.091205, 0.07569, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.078216, 0.065473, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.065865, 0.05557, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.054279, 0.046107, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.043579, 0.037205, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.03387, 0.029004, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.025247, 0.021613, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.017799, 0.01515, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.011596, 0.009718, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.006704, 0.005399, 0.2145)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2145)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.004286, 0.008269, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.007908, 0.014348, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.012572, 0.021998, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.018274, 0.031094, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.025006, 0.041503, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.032748, 0.053062, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.041473, 0.065603, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.051145, 0.07894, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.061698, 0.092884, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.073071, 0.107234, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.085184, 0.12179, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.097934, 0.13635, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.111217, 0.150716, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.124897, 0.164694, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.138876, 0.178119, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.153444, 0.190895, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.168209, 0.202471, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.182936, 0.212726, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.197378, 0.221592, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.211282, 0.229017, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.224394, 0.235001, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.23647, 0.239569, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.24729, 0.242769, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.256656, 0.244666, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.264409, 0.245337, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.270422, 0.244851, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.274615, 0.243274, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.276952, 0.240663, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.27738, 0.237185, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.275877, 0.233006, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.272517, 0.228152, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.267401, 0.222646, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.260648, 0.216511, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.252401, 0.209768, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.242807, 0.202422, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.232037, 0.194488, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.220269, 0.185958, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.207676, 0.176828, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.194439, 0.167095, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.180749, 0.156754, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.16678, 0.145812, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.152306, 0.134148, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.137659, 0.122256, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.123049, 0.110251, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.108646, 0.09823, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.094614, 0.086314, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.08111, 0.074629, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.068281, 0.063315, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.056254, 0.052514, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.045155, 0.042364, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.03509, 0.03302, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.026157, 0.024606, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.018445, 0.017253, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.012025, 0.011076, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.006963, 0.006167, 0.231)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.231)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.004184, 0.009092, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.007767, 0.015799, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.012388, 0.024245, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.01805, 0.034295, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.024752, 0.045807, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.03248, 0.058604, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.041215, 0.072504, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.050924, 0.087307, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.061551, 0.102805, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.073036, 0.11878, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.085305, 0.135013, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.098258, 0.151283, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.111793, 0.167373, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.125773, 0.183064, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.140102, 0.198179, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.155096, 0.212625, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.170361, 0.225794, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.185653, 0.237543, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.200708, 0.247785, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.215259, 0.256456, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.229032, 0.263538, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.241764, 0.269049, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.253217, 0.273028, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.263174, 0.275536, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.271463, 0.276647, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.277941, 0.276427, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.282522, 0.274946, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.285162, 0.272261, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.285795, 0.268549, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.284393, 0.263988, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.281031, 0.258609, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.275816, 0.252441, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.268876, 0.245516, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.260364, 0.237863, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.250436, 0.229496, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.239275, 0.220437, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.227072, 0.210689, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.214014, 0.200255, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.200297, 0.189142, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.186123, 0.177354, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.171679, 0.164905, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.15673, 0.151656, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.141607, 0.138155, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.126529, 0.124533, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.111674, 0.110906, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.097212, 0.097409, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.083306, 0.084187, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.070104, 0.071397, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.057739, 0.059199, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.046336, 0.047745, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.036003, 0.037209, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.026838, 0.027728, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.01893, 0.019447, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.01235, 0.012494, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.007164, 0.00697, 0.2475)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2475)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.004014, 0.009921, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007505, 0.017266, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.012018, 0.026519, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.017563, 0.037538, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.024146, 0.050172, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.03176, 0.064228, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.040395, 0.079513, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.050025, 0.095813, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.0606, 0.112901, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.072068, 0.130541, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.084361, 0.148495, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.097383, 0.166524, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.111035, 0.184389, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.125182, 0.201851, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.139732, 0.218714, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.155025, 0.234897, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.170672, 0.249728, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.186418, 0.263044, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.201988, 0.27474, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.217097, 0.28473, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.231454, 0.292985, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.244778, 0.29951, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.256813, 0.304335, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.267324, 0.307512, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.276122, 0.309114, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.283054, 0.309204, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.288021, 0.307851, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.290976, 0.305115, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.291838, 0.301181, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.290569, 0.29624, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.287247, 0.290325, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.281985, 0.283475, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.274919, 0.27573, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.26621, 0.267129, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.256023, 0.257693, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.244555, 0.247458, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.232008, 0.236434, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.218582, 0.224634, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.204485, 0.212076, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.189935, 0.198773, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.17513, 0.184752, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.159824, 0.169851, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.144346, 0.154672, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.128922, 0.139365, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.113736, 0.124065, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.098964, 0.108923, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.084772, 0.094102, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.07131, 0.079779, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.058712, 0.066129, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.047105, 0.053323, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.036595, 0.04155, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.02728, 0.030963, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.019247, 0.021722, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.012566, 0.013965, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.007303, 0.007805, 0.264)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.264)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.003775, 0.010754, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.007122, 0.01874, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.011461, 0.028808, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.01681, 0.040806, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.023182, 0.054572, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.03058, 0.069904, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.039002, 0.086594, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.048433, 0.104412, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.05883, 0.123116, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.070149, 0.142452, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.08233, 0.162164, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.095282, 0.181991, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.108912, 0.201675, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.12309, 0.220955, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.137726, 0.239618, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.153186, 0.257595, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.169091, 0.274152, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.185176, 0.289101, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.201154, 0.302319, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.216727, 0.313699, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.231587, 0.323197, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.245435, 0.330802, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.257996, 0.336534, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.269019, 0.340438, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.278297, 0.34258, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.285666, 0.343022, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.291017, 0.341831, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.294296, 0.339068, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.29541, 0.334926, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.294306, 0.329606, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.291068, 0.323149, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.285812, 0.315601, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.278683, 0.30701, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.269847, 0.297426, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.259482, 0.286881, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.247794, 0.275422, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.234997, 0.263069, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.221304, 0.249848, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.206936, 0.235787, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.192122, 0.220911, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.177073, 0.205258, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.161536, 0.188644, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.145828, 0.171726, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.130185, 0.154675, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.114795, 0.137642, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.099836, 0.120799, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.085479, 0.104326, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.071874, 0.088418, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.059155, 0.07327, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.047447, 0.059069, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.036854, 0.046023, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.027473, 0.034297, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.01939, 0.024066, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.012671, 0.015482, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.007379, 0.008666, 0.2805)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.2805)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.003466, 0.011584, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.006616, 0.020214, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.010715, 0.031099, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.015787, 0.04408, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.021856, 0.058986, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.028934, 0.075602, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.03703, 0.093708, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.04614, 0.113059, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.056228, 0.133398, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.067263, 0.154451, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.079192, 0.175947, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.091933, 0.197602, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.1054, 0.21914, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.119467, 0.240277, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.13405, 0.260782, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.149541, 0.280602, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.165573, 0.298939, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.181877, 0.315581, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.198153, 0.330382, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.214092, 0.343217, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.229368, 0.35402, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.243665, 0.362768, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.256692, 0.369466, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.268179, 0.374152, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.277906, 0.376883, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.285693, 0.377717, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.291423, 0.376721, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.295036, 0.373956, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.296422, 0.369622, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.295517, 0.36393, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.292406, 0.356925, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.287211, 0.348665, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.280082, 0.339206, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.271195, 0.32861, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.260734, 0.31692, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.248917, 0.304195, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.235969, 0.290469, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.222115, 0.275777, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.207587, 0.260161, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.192626, 0.24366, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.177456, 0.226324, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.161816, 0.207945, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.14601, 0.189235, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.130279, 0.170388, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.114815, 0.151572, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.0998, 0.132979, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.085404, 0.114808, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.071776, 0.097274, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.059049, 0.080589, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.047347, 0.064957, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.03677, 0.050605, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.027411, 0.037712, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.019353, 0.026468, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.012659, 0.017037, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.007389, 0.009551, 0.297)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.297)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.003088, 0.012407, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.005988, 0.021679, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.009777, 0.03338, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.014492, 0.047342, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.020164, 0.063387, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.026818, 0.081289, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.034473, 0.100814, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.043136, 0.121706, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.052785, 0.143689, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.063398, 0.166474, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.074933, 0.189769, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.087319, 0.213274, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.100477, 0.236691, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.114289, 0.259714, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.128677, 0.282095, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.144058, 0.303797, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.160084, 0.32396, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.176481, 0.342346, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.19294, 0.358786, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.20914, 0.373133, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.22474, 0.3853, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.239409, 0.395249, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.252837, 0.402969, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.264739, 0.408487, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.274877, 0.411854, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.283061, 0.413121, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.289163, 0.412352, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.293116, 0.40961, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.294795, 0.405102, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.294121, 0.399044, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.291181, 0.391491, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.286103, 0.382509, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.279042, 0.372164, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.270179, 0.360533, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.259709, 0.347667, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.247857, 0.33364, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.234861, 0.3185, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.220955, 0.302295, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.206382, 0.285081, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.191397, 0.266911, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.176232, 0.247848, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.160622, 0.227661, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.144854, 0.207115, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.129171, 0.186428, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.113769, 0.165788, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.09883, 0.145405, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.084523, 0.125498, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.070997, 0.106302, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.05838, 0.088048, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.046794, 0.070957, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.036333, 0.055273, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.027086, 0.041191, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.019131, 0.028916, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.012527, 0.018622, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.007332, 0.010454, 0.3135)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.3135)
boolstatus = Part.InsertCurveFileEnd()
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.002639, 0.013219, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.005235, 0.023127, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.008649, 0.035637, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.012924, 0.050574, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.018106, 0.067752, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.024229, 0.086934, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.031327, 0.107875, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.039419, 0.130305, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.048495, 0.153933, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.058547, 0.178453, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.069545, 0.203556, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.081428, 0.228922, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.09413, 0.254233, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.107539, 0.279162, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.121586, 0.303444, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.136713, 0.327059, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.152595, 0.349085, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.168955, 0.369258, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.185478, 0.387385, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.20183, 0.403294, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.217659, 0.416878, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.232617, 0.42808, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.246377, 0.436874, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.258639, 0.443273, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.26915, 0.447319, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.277706, 0.449057, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.284171, 0.448549, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.288469, 0.445857, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.29046, 0.441191, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.290049, 0.434778, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.287326, 0.426679, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.282422, 0.416968, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.275496, 0.405726, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.266736, 0.393038, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.256345, 0.378971, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.244556, 0.363614, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.231617, 0.347027, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.217771, 0.329275, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.203274, 0.310426, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.18839, 0.29055, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.17336, 0.269725, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.157917, 0.247693, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.142326, 0.225277, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.126831, 0.202716, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.111629, 0.180218, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.096903, 0.158014, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.082818, 0.136343, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.069522, 0.115459, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.057135, 0.095611, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.045778, 0.07704, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.035534, 0.060005, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.026491, 0.044718, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.01872, 0.031397, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.012273, 0.020231, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.007206, 0.011372, 0.33)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0, 0.33)
boolstatus = Part.InsertCurveFileEnd()
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", 0.0, 0.0, 0.0495, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", 0.0, 0.0, 0.066, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", 0.0, 0.0, 0.0825, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", 0.0, 0.0, 0.099, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", 0.0, 0.0, 0.11549999999999999, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", 0.0, 0.0, 0.132, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", 0.0, 0.0, 0.1485, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", 0.0, 0.0, 0.165, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", 0.0, 0.0, 0.18150000000000002, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", 0.0, 0.0, 0.198, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", 0.0, 0.0, 0.2145, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", 0.0, 0.0, 0.23099999999999998, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve13", "REFERENCECURVES", 0.0, 0.0, 0.2475, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve14", "REFERENCECURVES", 0.0, 0.0, 0.264, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve15", "REFERENCECURVES", 0.0, 0.0, 0.2805, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve16", "REFERENCECURVES", 0.0, 0.0, 0.297, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve17", "REFERENCECURVES", 0.0, 0.0, 0.3135, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve18", "REFERENCECURVES", 0.0, 0.0, 0.33, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
