Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00575, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005677, 0.000464, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005464, 0.000882, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005132, 0.001214, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.004714, 0.001427, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00425, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0034, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00255, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0017, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00085, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00085, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0017, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00255, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0034, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00425, 0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.004714, 0.001427, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005132, 0.001214, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005464, 0.000882, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005677, 0.000464, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00575, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005677, -0.000464, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005464, -0.000882, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.005132, -0.001214, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.004714, -0.001427, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00425, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0034, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00255, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0017, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.00085, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00085, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0017, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00255, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0034, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00425, -0.0015, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.004714, -0.001427, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005132, -0.001214, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005464, -0.000882, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.005677, -0.000464, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.00575, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00575, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005677, 0.000464, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005464, 0.000882, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005132, 0.001214, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.004714, 0.001427, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00425, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0034, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00255, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0017, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00085, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00085, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0017, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00255, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0034, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00425, 0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.004714, 0.001427, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005132, 0.001214, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005464, 0.000882, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005677, 0.000464, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00575, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005677, -0.000464, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005464, -0.000882, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.005132, -0.001214, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.004714, -0.001427, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00425, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0034, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00255, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0017, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.00085, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00085, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0017, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00255, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0034, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00425, -0.0015, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.004714, -0.001427, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005132, -0.001214, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005464, -0.000882, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.005677, -0.000464, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.00575, 0.0, 0.01143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.005838, -0.001779, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005566, -0.001552, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.00535, -0.0014, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005076, -0.001212, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004746, -0.000993, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004361, -0.00075, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003926, -0.000488, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003443, -0.000214, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002918, 6.5e-05, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002355, 0.000342, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001759, 0.000612, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001138, 0.000866, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000496, 0.001101, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000159, 0.001311, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000819, 0.00149, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.00148, 0.001636, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002148, 0.001735, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002801, 0.001775, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003432, 0.001758, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004029, 0.001688, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004586, 0.001573, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005094, 0.00142, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005546, 0.001237, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005935, 0.001034, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006258, 0.00082, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.00651, 0.000604, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006688, 0.000391, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006792, 0.000189, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.00682, 0.0, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006774, -0.000166, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006657, -0.000302, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006471, -0.000409, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006219, -0.000488, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005906, -0.000543, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005536, -0.000578, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005114, -0.000596, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004646, -0.000602, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004137, -0.000603, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003592, -0.000605, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003017, -0.000612, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002418, -0.000632, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001799, -0.000669, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001153, -0.000722, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000498, -0.000779, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000158, -0.000843, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000808, -0.000913, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001445, -0.000991, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002061, -0.001076, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.00265, -0.001166, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003206, -0.001258, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003722, -0.001352, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004192, -0.001443, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004611, -0.001529, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004975, -0.001607, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005278, -0.001674, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005518, -0.001729, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005838, -0.001779, 0.01905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.01211, -0.006841, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01173, -0.006504, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011427, -0.006265, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01104, -0.005967, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010572, -0.005615, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010026, -0.005217, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009407, -0.00478, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008718, -0.004312, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007965, -0.003822, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007155, -0.003318, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.006296, -0.00281, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.005396, -0.002306, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004462, -0.001814, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003506, -0.001342, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.002536, -0.000897, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.001563, -0.000487, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.000572, -0.000121, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.000406, 0.00018, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001356, 0.000414, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.002264, 0.000583, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003117, 0.00069, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003901, 0.000738, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004605, 0.000735, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005218, 0.000686, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005732, 0.0006, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006139, 0.000483, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006436, 0.000341, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006619, 0.000179, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006687, 0.0, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00664, -0.000185, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006482, -0.000369, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006217, -0.00055, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005849, -0.000731, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005385, -0.000911, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004834, -0.001093, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004202, -0.00128, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003499, -0.001473, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.002733, -0.001678, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001914, -0.001896, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00105, -0.002133, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.000151, -0.002392, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.000773, -0.002676, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.001738, -0.002987, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.002716, -0.003307, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003694, -0.003632, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004661, -0.003963, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.005608, -0.004296, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.006524, -0.004627, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007398, -0.004952, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008221, -0.005267, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008984, -0.005567, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009679, -0.005846, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010298, -0.0061, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010834, -0.006323, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011281, -0.006512, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011635, -0.006663, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01211, -0.006841, 0.0381)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.016814, -0.008449, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016339, -0.00803, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01596, -0.007734, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015476, -0.007364, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.014891, -0.006927, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.014208, -0.006432, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.013432, -0.00589, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012571, -0.005309, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.011629, -0.004701, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.010617, -0.004077, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009543, -0.003446, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.008417, -0.002821, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.00725, -0.002212, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.006055, -0.001627, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.004843, -0.001078, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003627, -0.00057, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.002389, -0.000118, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.001168, 0.000253, 0.05715)
boolstatus = Part.InsertCurveFilePoint(1.9e-05, 0.000541, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.001152, 0.000748, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002217, 0.000877, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.003195, 0.000934, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004073, 0.000926, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004838, 0.000863, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005479, 0.000753, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005987, 0.000605, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006356, 0.000426, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006584, 0.000223, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006609, -0.000231, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006411, -0.000459, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006079, -0.000684, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005619, -0.000908, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00504, -0.001131, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004351, -0.001355, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.003562, -0.001585, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002684, -0.001823, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.001728, -0.002075, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.000704, -0.002344, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.000374, -0.002636, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.001497, -0.002955, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.002652, -0.003305, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003857, -0.003689, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.005078, -0.004082, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.0063, -0.004484, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.007509, -0.004892, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.008691, -0.005303, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009835, -0.005712, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.010927, -0.006114, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.011955, -0.006503, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012909, -0.006873, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.013777, -0.007218, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01455, -0.007532, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01522, -0.007809, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015779, -0.008043, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016221, -0.008229, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016814, -0.008449, 0.05715)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.018917, -0.006898, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018378, -0.006496, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017951, -0.006216, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017407, -0.005866, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.016751, -0.005455, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015985, -0.004991, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015119, -0.004485, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.014157, -0.003946, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.013109, -0.003384, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.011984, -0.002812, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.010793, -0.002238, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.009548, -0.001675, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.008262, -0.001131, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.006947, -0.000617, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.005618, -0.000141, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.004287, 0.00029, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.002939, 0.000661, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.001615, 0.000947, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.000336, 0.001149, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.000881, 0.001269, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.002018, 0.001313, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003058, 0.001289, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003986, 0.001205, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004789, 0.001071, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005457, 0.000899, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005981, 0.000699, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006356, 0.000478, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006579, 0.000243, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006648, 0.0, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006567, -0.000239, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006337, -0.000463, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005966, -0.000673, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005461, -0.000869, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004829, -0.001054, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004081, -0.001232, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003226, -0.001407, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.002277, -0.001583, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.001244, -0.001766, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.000139, -0.001962, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.001027, -0.002176, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.002242, -0.002416, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.003494, -0.002687, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.004801, -0.002988, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.006127, -0.003298, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.007453, -0.003617, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.008767, -0.003944, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.010054, -0.004275, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.011299, -0.004609, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.012488, -0.004939, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01361, -0.005261, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01465, -0.00557, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015598, -0.00586, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.016443, -0.006125, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017176, -0.006359, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017787, -0.006558, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01827, -0.006717, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018917, -0.006898, 0.0762)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.019013, -0.005426, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018461, -0.005059, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018026, -0.004806, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.017473, -0.004491, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016804, -0.004122, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016026, -0.003706, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.015146, -0.003254, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.014171, -0.002774, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.01311, -0.002278, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.011972, -0.001774, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.01077, -0.001273, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.009515, -0.000785, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.008219, -0.000319, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.006898, 0.000117, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.005565, 0.000515, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004232, 0.000869, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.002885, 0.001161, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.001567, 0.001373, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.000298, 0.001503, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.000907, 0.001557, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002028, 0.001539, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.00305, 0.00146, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003959, 0.001328, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.004742, 0.001154, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.00539, 0.000949, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005896, 0.000723, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006253, 0.000486, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.00646, 0.000243, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006515, 0.0, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006422, -0.000231, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006184, -0.000439, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005808, -0.000626, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.0053, -0.000792, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.004668, -0.000941, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003922, -0.001076, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003072, -0.001202, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002129, -0.001325, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.001102, -0.00145, 0.09525)
boolstatus = Part.InsertCurveFilePoint(4.0e-06, -0.001584, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.001155, -0.001733, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.002363, -0.001904, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.00361, -0.002104, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004912, -0.00233, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.006233, -0.002565, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.007556, -0.002808, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.008867, -0.00306, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.010151, -0.003318, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.011394, -0.003579, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.012582, -0.003841, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.013703, -0.004098, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.014743, -0.004347, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.015691, -0.004581, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016537, -0.004797, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.017271, -0.004989, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.017883, -0.005152, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018367, -0.005283, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.019013, -0.005426, 0.09525)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.017298, -0.004135, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016783, -0.003818, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016378, -0.003601, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.015863, -0.003331, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.015242, -0.003016, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.014519, -0.002662, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.013702, -0.002277, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.012798, -0.001871, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.011814, -0.001452, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.010761, -0.001029, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.009649, -0.000611, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.008489, -0.000206, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.007293, 0.000178, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.006073, 0.000534, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.004845, 0.000854, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.003619, 0.001134, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.002381, 0.001358, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.001173, 0.001509, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-1.1e-05, 0.001587, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001089, 0.001598, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00211, 0.001547, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00304, 0.001441, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003864, 0.001292, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004573, 0.001108, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005158, 0.000901, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005611, 0.000679, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00593, 0.000451, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00611, 0.000223, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006153, 0.0, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006061, -0.000208, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005837, -0.00039, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005488, -0.000548, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00502, -0.000683, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004439, -0.000799, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003755, -0.000899, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.002976, -0.000987, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.002111, -0.001068, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001171, -0.001149, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.000166, -0.001237, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.000896, -0.001336, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.002003, -0.001454, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.003146, -0.001596, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.004341, -0.001761, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.005553, -0.001933, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.006767, -0.002113, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.00797, -0.0023, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.009149, -0.002494, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.010291, -0.002693, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.011383, -0.002894, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.012413, -0.003093, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01337, -0.003287, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.014242, -0.00347, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01502, -0.00364, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.015695, -0.003791, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016258, -0.003921, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016704, -0.004025, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.017298, -0.004135, 0.1143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.015836, -0.003219, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015364, -0.002944, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014993, -0.002757, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014522, -0.002524, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013954, -0.002253, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013293, -0.001949, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.012546, -0.001619, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01172, -0.001272, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010821, -0.000915, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.00986, -0.000556, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.008846, -0.000203, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.007788, 0.000138, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.006699, 0.000458, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.005589, 0.000753, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004472, 0.001015, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.003358, 0.001241, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.002235, 0.001416, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.001139, 0.001525, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-8.8e-05, 0.001571, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000907, 0.001556, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001829, 0.001487, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002666, 0.001371, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003408, 0.001218, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004045, 0.001037, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004569, 0.000836, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004974, 0.000626, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005256, 0.000413, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005415, 0.000203, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005448, 0.0, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.00536, -0.000186, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005154, -0.000346, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004835, -0.00048, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004409, -0.000592, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003881, -0.000684, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003261, -0.000759, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002555, -0.000821, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001772, -0.000876, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000921, -0.000929, 0.13335)
boolstatus = Part.InsertCurveFilePoint(1.0e-05, -0.000985, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.000952, -0.001052, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.001955, -0.001134, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.002991, -0.001237, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004075, -0.00136, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.005174, -0.001488, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.006275, -0.001624, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.007366, -0.001767, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.008436, -0.001916, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.009472, -0.002071, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010464, -0.002228, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.011399, -0.002385, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.012268, -0.002539, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01306, -0.002686, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013767, -0.002822, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01438, -0.002944, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014892, -0.003048, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015297, -0.003132, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015836, -0.003219, 0.13335)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.013676, -0.002206, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013273, -0.001986, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012957, -0.001837, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012556, -0.001653, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012072, -0.001438, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011509, -0.001198, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010874, -0.000938, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010171, -0.000666, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009408, -0.000387, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.008592, -0.000108, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007731, 0.000165, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.006834, 0.000426, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.005911, 0.00067, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004972, 0.000892, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004027, 0.001086, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.003085, 0.00125, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002137, 0.00137, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001214, 0.001437, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.000329, 0.00145, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.000506, 0.001414, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001279, 0.001335, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001981, 0.001218, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.0026, 0.001072, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003131, 0.000904, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003567, 0.000723, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003902, 0.000537, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004135, 0.000351, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004263, 0.000171, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004286, 0.0, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004208, -0.000154, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004031, -0.000283, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00376, -0.000389, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003399, -0.000473, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002953, -0.000538, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00243, -0.000587, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001835, -0.000622, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001176, -0.00065, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.00046, -0.000674, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.000307, -0.0007, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001117, -0.000733, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001962, -0.000779, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002835, -0.000841, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.003749, -0.000919, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004675, -0.001002, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.005604, -0.00109, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.006524, -0.001184, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007427, -0.001284, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.008301, -0.00139, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009138, -0.001499, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009928, -0.001609, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010662, -0.001718, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011331, -0.001823, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011928, -0.00192, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012446, -0.002009, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012879, -0.002084, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013222, -0.002145, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013676, -0.002206, 0.1524)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.011624, -0.00144, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011303, -0.001273, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011052, -0.001162, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010732, -0.001023, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010348, -0.000862, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009901, -0.000682, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009397, -0.000489, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008839, -0.000286, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008234, -7.9e-05, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007587, 0.000127, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006905, 0.000328, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006194, 0.000519, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005464, 0.000696, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004721, 0.000854, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003974, 0.000992, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00323, 0.001105, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002481, 0.001185, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001753, 0.001222, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001057, 0.001217, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.0004, 0.001176, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000208, 0.0011, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000758, 0.000997, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001243, 0.000871, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001658, 0.000731, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001998, 0.000581, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002259, 0.000429, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002439, 0.000279, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002537, 0.000135, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002553, 0.0, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002488, -0.00012, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002347, -0.000219, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002132, -0.000298, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001846, -0.000358, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001495, -0.000402, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001082, -0.000431, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000613, -0.00045, 0.17145)
boolstatus = Part.InsertCurveFilePoint(9.4e-05, -0.00046, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000471, -0.000468, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001075, -0.000476, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001713, -0.000488, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002379, -0.00051, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003067, -0.000545, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003787, -0.000591, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004518, -0.000641, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005251, -0.000695, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005977, -0.000754, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006689, -0.000818, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007379, -0.000887, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00804, -0.000959, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008663, -0.001032, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009242, -0.001106, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009771, -0.001177, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010243, -0.001244, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010652, -0.001305, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010994, -0.001358, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011265, -0.0014, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011624, -0.00144, 0.17145)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.00909, -0.000807, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00888, -0.000702, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008716, -0.000631, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008507, -0.000544, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008256, -0.000443, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007964, -0.00033, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007634, -0.000209, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00727, -8.2e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006875, 4.6e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006453, 0.000175, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006008, 0.000299, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005545, 0.000417, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005068, 0.000525, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004584, 0.000621, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004098, 0.000704, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003613, 0.00077, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003126, 0.000815, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002653, 0.000833, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.0022, 0.000824, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001774, 0.000791, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00138, 0.000736, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001024, 0.000664, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000709, 0.000578, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000441, 0.000483, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000222, 0.000383, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-5.3e-05, 0.000281, 0.1905)
boolstatus = Part.InsertCurveFilePoint(6.2e-05, 0.000182, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000124, 8.8e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000133, 0.0, 0.1905)
boolstatus = Part.InsertCurveFilePoint(9.0e-05, -7.7e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-2.0e-06, -0.00014, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000143, -0.00019, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000329, -0.000226, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000558, -0.000251, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000826, -0.000267, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001131, -0.000274, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001468, -0.000277, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001835, -0.000276, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002228, -0.000276, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002642, -0.000279, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003075, -0.000287, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003522, -0.000303, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003991, -0.000326, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004466, -0.000352, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004943, -0.000381, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005415, -0.000412, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005878, -0.000448, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006327, -0.000486, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006757, -0.000527, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007162, -0.000569, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00754, -0.000612, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007884, -0.000653, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008191, -0.000692, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008457, -0.000728, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00868, -0.000759, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.008856, -0.000784, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00909, -0.000807, 0.1905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.00575, -1.8369701987210296e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.00575, -1.8369701987210296e-19, 0.01143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.005838249999999998, -0.00177899, 0.01905, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.012109649999999998, -0.00684126, 0.0381, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.01681413, -0.00844928, 0.05715, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.018916779999999998, -0.00689803, 0.0762, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.01901309, -0.005426179999999999, 0.09525, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.01729758, -0.004135, 0.1143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.01583616, -0.0032189700000000003, 0.13335, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.013676349999999997, -0.00220553, 0.1524, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.011623750000000002, -0.0014399900000000002, 0.17145000000000002, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.009089719999999997, -0.00080691, 0.1905, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
