Dim swApp As Object
Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long
Sub main()
Set swApp = _
Application.SldWorks
Set Part = swApp.ActiveDoc
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006951, 0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006809, 0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006588, 0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006309, 0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0048, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0024, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0012, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0012, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0024, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0048, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006, 0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006309, 0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006588, 0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006809, 0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006951, 0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006951, -0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006809, -0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006588, -0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006309, -0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.006, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0048, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0024, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0012, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0012, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0024, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.0048, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006, -0.001, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006309, -0.000951, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.000809, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006809, -0.000588, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.006951, -0.000309, 0.0)
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.0)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve1")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006951, 0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006809, 0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006588, 0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006309, 0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0048, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0036, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0024, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0012, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0012, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0024, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0036, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0048, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006, 0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006309, 0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006588, 0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006809, 0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006951, 0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006951, -0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006809, -0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006588, -0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006309, -0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.006, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0048, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0036, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0024, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0012, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(0.0, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0012, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0024, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0036, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.0048, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006, -0.001, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006309, -0.000951, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.000809, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006809, -0.000588, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.006951, -0.000309, 0.01143)
boolstatus = Part.InsertCurveFilePoint(-0.007, 0.0, 0.01143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve2")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.008272, -0.002121, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007942, -0.001886, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007682, -0.001727, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007351, -0.001532, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006953, -0.001303, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006489, -0.001049, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005964, -0.000774, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005383, -0.000487, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004752, -0.000193, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004075, 0.0001, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.00336, 0.000387, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.002615, 0.000659, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001846, 0.000911, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001062, 0.001139, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000272, 0.001337, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000517, 0.001501, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001313, 0.001618, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002091, 0.001675, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002839, 0.001674, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003548, 0.001621, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004207, 0.00152, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004806, 0.001379, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005338, 0.001208, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005796, 0.001015, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006174, 0.000808, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006467, 0.000598, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006674, 0.000389, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006791, 0.000189, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.00682, 0.0, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006761, -0.000168, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006618, -0.000308, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006394, -0.00042, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.006093, -0.000506, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005719, -0.00057, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.005279, -0.000614, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004777, -0.000643, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.004221, -0.000662, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.003615, -0.000677, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002968, -0.000692, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.002284, -0.000715, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.001571, -0.000751, 0.01905)
boolstatus = Part.InsertCurveFilePoint(0.000835, -0.000804, 0.01905)
boolstatus = Part.InsertCurveFilePoint(6.6e-05, -0.000874, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.000714, -0.000949, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.001496, -0.001031, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.00227, -0.001119, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003029, -0.001214, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.003764, -0.001315, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.004466, -0.001421, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005129, -0.001528, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.005745, -0.001636, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006306, -0.00174, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.006807, -0.001837, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007241, -0.001925, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.007603, -0.002001, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.00789, -0.002062, 0.01905)
boolstatus = Part.InsertCurveFilePoint(-0.008272, -0.002121, 0.01905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve3")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.016585, -0.00847, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.016115, -0.008053, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01574, -0.007757, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015261, -0.007388, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014682, -0.006952, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014006, -0.006459, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.013238, -0.005918, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.012385, -0.005339, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.011453, -0.004732, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010451, -0.004108, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009388, -0.003479, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008272, -0.002855, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007117, -0.002245, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.005932, -0.001661, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004732, -0.001111, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003527, -0.000603, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.0023, -0.00015, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.00109, 0.000222, 0.0381)
boolstatus = Part.InsertCurveFilePoint(8.6e-05, 0.000513, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001211, 0.000722, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.002267, 0.000854, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.003238, 0.000914, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004109, 0.00091, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004868, 0.00085, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005504, 0.000743, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006009, 0.000598, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006376, 0.000422, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006602, 0.000221, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006687, 0.0, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006629, -0.00023, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006434, -0.000457, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.006105, -0.000681, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005649, -0.000904, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.005075, -0.001128, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.004392, -0.001353, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00361, -0.001584, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.00274, -0.001824, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.001792, -0.002077, 0.0381)
boolstatus = Part.InsertCurveFilePoint(0.000778, -0.002348, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.000292, -0.002641, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.001405, -0.002962, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.002549, -0.003314, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.003744, -0.003699, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.004954, -0.004094, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.006165, -0.004497, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.007363, -0.004907, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.008536, -0.005318, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.009669, -0.005728, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.010751, -0.006131, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.01177, -0.006521, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.012715, -0.006892, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.013575, -0.007238, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.014342, -0.007552, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015005, -0.007829, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015559, -0.008063, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.015997, -0.00825, 0.0381)
boolstatus = Part.InsertCurveFilePoint(-0.016585, -0.00847, 0.0381)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve4")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.022909, -0.010642, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.02231, -0.010115, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021832, -0.009741, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021223, -0.009275, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020486, -0.008725, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.019626, -0.008102, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.018649, -0.007419, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.017564, -0.006687, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016378, -0.005922, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015103, -0.005135, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01375, -0.004341, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012332, -0.003554, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.010862, -0.002786, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009356, -0.00205, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.007831, -0.001357, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.006298, -0.000718, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.004739, -0.000149, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003201, 0.000318, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.001707, 0.000681, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.000279, 0.000942, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.001062, 0.001104, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002294, 0.001176, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.0034, 0.001167, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004364, 0.001087, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00517, 0.000949, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00581, 0.000762, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006276, 0.000537, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006562, 0.000281, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006668, 0.0, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006594, -0.000291, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.006344, -0.000578, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005926, -0.000862, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.005346, -0.001143, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.004617, -0.001424, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.003749, -0.001707, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.002756, -0.001997, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.00165, -0.002297, 0.05715)
boolstatus = Part.InsertCurveFilePoint(0.000445, -0.002613, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.000843, -0.002952, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.002202, -0.00332, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.003616, -0.003722, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.005071, -0.004163, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.006588, -0.004646, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.008126, -0.005142, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.009665, -0.005648, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.011188, -0.006162, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.012678, -0.006679, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.014118, -0.007194, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.015493, -0.0077, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.016789, -0.008191, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.01799, -0.008657, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.019083, -0.009092, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020057, -0.009487, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.020901, -0.009836, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.021605, -0.01013, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.022161, -0.010365, 0.05715)
boolstatus = Part.InsertCurveFilePoint(-0.022909, -0.010642, 0.05715)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve5")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.025538, -0.008685, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.02486, -0.008179, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024322, -0.007825, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.023638, -0.007385, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.022811, -0.006868, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.021847, -0.006284, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.020756, -0.005646, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.019545, -0.004968, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018226, -0.004261, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01681, -0.00354, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015311, -0.002818, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.013743, -0.002109, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.012123, -0.001425, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.010467, -0.000777, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.008795, -0.000177, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.007119, 0.000366, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.005422, 0.000832, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.003756, 0.001192, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.002145, 0.001446, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.000613, 0.001598, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.000818, 0.001653, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.002128, 0.001622, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003296, 0.001517, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004307, 0.001349, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005148, 0.001132, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005809, 0.00088, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006281, 0.000601, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006561, 0.000306, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006648, 0.0, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006545, -0.000301, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.006257, -0.000583, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.00579, -0.000847, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.005153, -0.001094, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.004357, -0.001327, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.003416, -0.001551, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.00234, -0.001771, 0.0762)
boolstatus = Part.InsertCurveFilePoint(0.001145, -0.001993, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.000155, -0.002223, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.001547, -0.00247, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.003015, -0.00274, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.004544, -0.003042, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.00612, -0.003382, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.007766, -0.003762, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.009435, -0.004153, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.011106, -0.004554, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01276, -0.004965, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.01438, -0.005383, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.015947, -0.005802, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.017445, -0.006218, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.018856, -0.006624, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.020166, -0.007013, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.02136, -0.007378, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.022424, -0.007711, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.023346, -0.008006, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024116, -0.008256, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.024724, -0.008457, 0.0762)
boolstatus = Part.InsertCurveFilePoint(-0.025538, -0.008685, 0.0762)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve6")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.024231, -0.006535, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.023566, -0.006093, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.023042, -0.005788, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.022375, -0.005409, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.02157, -0.004964, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.020634, -0.004463, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.019573, -0.003919, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.018399, -0.003341, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.01712, -0.002743, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.015751, -0.002137, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.014303, -0.001533, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.012791, -0.000946, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.011231, -0.000384, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.009639, 0.000141, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.008033, 0.00062, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.006428, 0.001046, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004806, 0.001399, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.003219, 0.001653, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.00169, 0.00181, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.00024, 0.001875, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.001111, 0.001854, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002342, 0.001758, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003436, 0.001599, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.00438, 0.001389, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.00516, 0.001143, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005769, 0.000871, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.0062, 0.000585, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006448, 0.000293, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006515, 0.0, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006403, -0.000278, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.006117, -0.000529, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005663, -0.000753, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.005051, -0.000954, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.004291, -0.001133, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.003393, -0.001296, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.002369, -0.001448, 0.09525)
boolstatus = Part.InsertCurveFilePoint(0.001232, -0.001595, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-4.0e-06, -0.001746, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.001327, -0.001907, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.002723, -0.002087, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.004178, -0.002293, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.005679, -0.002533, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.007248, -0.002806, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.008839, -0.003089, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.010432, -0.003382, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.012011, -0.003685, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.013557, -0.003996, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.015054, -0.004311, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.016485, -0.004626, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.017835, -0.004936, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.019088, -0.005235, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.02023, -0.005518, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.021249, -0.005777, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.022132, -0.006008, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.02287, -0.006204, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.023453, -0.006362, 0.09525)
boolstatus = Part.InsertCurveFilePoint(-0.024231, -0.006535, 0.09525)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve7")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.021988, -0.004962, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.02137, -0.004582, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020884, -0.004321, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020266, -0.003997, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.019521, -0.003619, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.018654, -0.003194, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.017674, -0.002733, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016588, -0.002245, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.015408, -0.001743, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.014144, -0.001235, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.012809, -0.000733, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.011417, -0.000247, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.009982, 0.000214, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.008519, 0.000641, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.007045, 0.001025, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.005573, 0.001361, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.004088, 0.00163, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.002638, 0.001811, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.001244, 0.001905, 0.1143)
boolstatus = Part.InsertCurveFilePoint(7.6e-05, 0.001918, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001302, 0.001856, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.002417, 0.00173, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003406, 0.00155, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004257, 0.00133, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004959, 0.001081, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005503, 0.000815, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005885, 0.000541, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006102, 0.000268, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006153, 0.0, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.006042, -0.000249, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005774, -0.000468, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.005355, -0.000657, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004793, -0.00082, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.004096, -0.000959, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.003275, -0.001078, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.00234, -0.001184, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.001303, -0.001282, 0.1143)
boolstatus = Part.InsertCurveFilePoint(0.000175, -0.001379, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.001032, -0.001484, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.002306, -0.001603, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.003634, -0.001744, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.005006, -0.001915, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.00644, -0.002113, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.007895, -0.00232, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.009352, -0.002535, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.010795, -0.00276, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01221, -0.002993, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01358, -0.003232, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.01489, -0.003473, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.016126, -0.003712, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.017274, -0.003944, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.018321, -0.004165, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.019255, -0.004368, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020064, -0.00455, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.020741, -0.004705, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.021276, -0.004829, 0.1143)
boolstatus = Part.InsertCurveFilePoint(-0.021988, -0.004962, 0.1143)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve8")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.019421, -0.003717, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.018869, -0.003397, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.018436, -0.003179, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.017885, -0.002908, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01722, -0.002592, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.016448, -0.002238, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015575, -0.001855, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014609, -0.001451, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013559, -0.001036, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.012435, -0.000619, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01125, -0.000208, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010014, 0.000188, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.008741, 0.00056, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.007444, 0.000902, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.006138, 0.001206, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004836, 0.001467, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.003524, 0.00167, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.002244, 0.001795, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.001015, 0.001846, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000146, 0.001827, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001223, 0.001744, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002202, 0.001608, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003068, 0.001427, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003811, 0.001214, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004422, 0.000979, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004895, 0.000732, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005225, 0.000482, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005409, 0.000237, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005448, 0.0, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005345, -0.000217, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.005104, -0.000403, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004731, -0.00056, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.004233, -0.00069, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.003617, -0.000796, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002892, -0.000882, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.002067, -0.000954, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.001152, -0.001016, 0.13335)
boolstatus = Part.InsertCurveFilePoint(0.000158, -0.001076, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.000906, -0.00114, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.00203, -0.001215, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.003202, -0.001309, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.004412, -0.001427, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.005679, -0.001569, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.006963, -0.001717, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.00825, -0.001873, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.009525, -0.002038, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.010775, -0.00221, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.011985, -0.002389, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.013143, -0.00257, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.014236, -0.002752, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.015252, -0.00293, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.016177, -0.0031, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.017004, -0.003257, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.01772, -0.003398, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.018319, -0.003519, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.018792, -0.003617, 0.13335)
boolstatus = Part.InsertCurveFilePoint(-0.019421, -0.003717, 0.13335)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve9")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.016513, -0.002554, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.016046, -0.002299, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.01568, -0.002127, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.015215, -0.001913, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.014654, -0.001665, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.014003, -0.001387, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013268, -0.001087, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012454, -0.000771, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.01157, -0.000449, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010625, -0.000125, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009629, 0.000191, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00859, 0.000494, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007522, 0.000776, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.006434, 0.001032, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00534, 0.001257, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.004249, 0.001447, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.003151, 0.001587, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002083, 0.001663, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001058, 0.001679, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-9.1e-05, 0.001638, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.000805, 0.001545, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001617, 0.00141, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002334, 0.001241, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002949, 0.001047, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003453, 0.000838, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003841, 0.000622, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004111, 0.000407, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004259, 0.000198, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004286, 0.0, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.004195, -0.000178, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003991, -0.000328, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003677, -0.000451, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.003259, -0.000548, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002743, -0.000623, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.002137, -0.000679, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.001448, -0.000721, 0.1524)
boolstatus = Part.InsertCurveFilePoint(0.000685, -0.000753, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.000145, -0.000781, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.001032, -0.000811, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00197, -0.000849, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.002948, -0.000902, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.003959, -0.000974, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.005017, -0.001064, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.00609, -0.00116, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.007166, -0.001262, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.008231, -0.001371, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.009276, -0.001487, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.010289, -0.00161, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.011258, -0.001736, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.012172, -0.001863, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013022, -0.001989, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.013797, -0.002111, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.014488, -0.002224, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.015088, -0.002326, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.015589, -0.002413, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.015986, -0.002484, 0.1524)
boolstatus = Part.InsertCurveFilePoint(-0.016513, -0.002554, 0.1524)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve10")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.012609, -0.00154, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.012266, -0.001362, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011997, -0.001242, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011656, -0.001094, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011245, -0.000922, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010767, -0.00073, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010228, -0.000523, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009631, -0.000306, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008984, -8.5e-05, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008292, 0.000136, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007562, 0.000351, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006802, 0.000555, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.006021, 0.000744, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005226, 0.000914, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004427, 0.001061, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003631, 0.001182, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002831, 0.001267, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002053, 0.001307, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001307, 0.001302, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000605, 0.001257, 0.17145)
boolstatus = Part.InsertCurveFilePoint(4.5e-05, 0.001177, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000633, 0.001066, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001152, 0.000932, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001596, 0.000782, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.00196, 0.000622, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002239, 0.000459, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002431, 0.000298, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002536, 0.000145, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002553, 0.0, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002484, -0.000128, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002333, -0.000234, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.002103, -0.000319, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001797, -0.000383, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.001421, -0.00043, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.00098, -0.000461, 0.17145)
boolstatus = Part.InsertCurveFilePoint(0.000478, -0.000481, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-7.7e-05, -0.000492, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.000681, -0.0005, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.001327, -0.000509, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002009, -0.000522, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.002721, -0.000546, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.003458, -0.000583, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.004228, -0.000632, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00501, -0.000685, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.005793, -0.000743, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00657, -0.000806, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.007331, -0.000875, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.00807, -0.000948, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.008776, -0.001025, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.009443, -0.001104, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010062, -0.001183, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.010628, -0.001259, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011132, -0.001331, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.01157, -0.001396, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.011936, -0.001452, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.012225, -0.001497, 0.17145)
boolstatus = Part.InsertCurveFilePoint(-0.012609, -0.00154, 0.17145)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve11")
Part.InsertCurveFileBegin
boolstatus = Part.InsertCurveFilePoint(-0.007458, -0.000664, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007285, -0.000577, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00715, -0.00052, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006978, -0.000448, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006771, -0.000365, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006531, -0.000272, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00626, -0.000172, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00596, -6.8e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005635, 3.8e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005287, 0.000144, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004921, 0.000246, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00454, 0.000343, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004148, 0.000432, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003749, 0.000511, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003349, 0.000579, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00295, 0.000634, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002549, 0.000671, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00216, 0.000685, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001787, 0.000678, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001437, 0.000651, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001112, 0.000606, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000819, 0.000546, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00056, 0.000476, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000339, 0.000397, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000159, 0.000315, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-2.0e-05, 0.000232, 0.1905)
boolstatus = Part.InsertCurveFilePoint(7.5e-05, 0.00015, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000126, 7.2e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(0.000133, 0.0, 0.1905)
boolstatus = Part.InsertCurveFilePoint(9.8e-05, -6.4e-05, 0.1905)
boolstatus = Part.InsertCurveFilePoint(2.2e-05, -0.000116, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-9.4e-05, -0.000156, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000247, -0.000186, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000435, -0.000207, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000656, -0.00022, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.000907, -0.000226, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001185, -0.000228, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.001487, -0.000227, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00181, -0.000227, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002151, -0.000229, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002507, -0.000236, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.002876, -0.000249, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003261, -0.000269, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.003652, -0.00029, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004044, -0.000313, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004433, -0.000339, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.004814, -0.000368, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005184, -0.0004, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005538, -0.000433, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.005871, -0.000468, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006182, -0.000503, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006465, -0.000538, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006718, -0.00057, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.006937, -0.000599, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.00712, -0.000625, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007265, -0.000645, 0.1905)
boolstatus = Part.InsertCurveFilePoint(-0.007458, -0.000664, 0.1905)
boolstatus = Part.InsertCurveFileEnd()
boolstatus = Part.SelectedFeatureProperties(0, 0, 0, 0, 0, 0, 0, 1, 0, "Curve12")
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("Curve1", "REFERENCECURVES", -0.007, -1.2246467991473531e-19, 0.0, False, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve2", "REFERENCECURVES", -0.007, -1.2246467991473531e-19, 0.01143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve3", "REFERENCECURVES", -0.00827179, -0.002121, 0.01905, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve4", "REFERENCECURVES", -0.01658494, -0.00847013, 0.0381, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve5", "REFERENCECURVES", -0.02290859, -0.01064222, 0.05715, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve6", "REFERENCECURVES", -0.025537989999999997, -0.00868457, 0.0762, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve7", "REFERENCECURVES", -0.02423052, -0.006535180000000001, 0.09525, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve8", "REFERENCECURVES", -0.02198773, -0.004961999999999999, 0.1143, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve9", "REFERENCECURVES", -0.01942149, -0.0037168199999999996, 0.13335, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve10", "REFERENCECURVES", -0.016512549999999997, -0.00255377, 0.1524, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve11", "REFERENCECURVES", -0.01260928, -0.0015401, 0.17145000000000002, True, 1, Nothing,0)
boolstatus = Part.Extension.SelectByID2("Curve12", "REFERENCECURVES", -0.007457649999999997, -0.00066413, 0.1905, True, 1, Nothing,0)
Part.FeatureManager.InsertProtrusionBlend False, True, False, 1, 6, 6, 1, 1, True, True, False, 0, 0, 0, True, True, True
End Sub
